#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Expands the dossier dataset to cover the entire document accurately,
including all municipalities across the 19 departments.
"""
import json
import os

with open("src/data/municipalities.json", "r", encoding="utf-8") as f:
    existing = {m["id"]: m for m in json.load(f)}

more_records = [
    # ATLÁNTICO
    {
        "id": "atlantico-puertocolombia",
        "name": "Puerto Colombia",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 117,
        "votos": 15357,
        "porcentaje": 60.70,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Sergio Antonio Carrascal Gómez", "Los Costeños", "Los Pepes"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Zona costera de alta valorización y puertos marítimos menores (Salgar).",
        "analisisOrdenPublico": "Acopio de cargamentos ilícitos antes de despacho marítimo. Disputas entre Los Costeños y Los Pepes con atentados sicariales a vehículos familiares.",
        "alertasDestacadas": "Ataques sicariales en corredores turísticos.",
        "coordinates": {"lat": 10.987, "lng": -74.954}
    },
    {
        "id": "atlantico-tubara",
        "name": "Tubará",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 34,
        "votos": 4890,
        "porcentaje": 65.33,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Sergio Antonio Carrascal Gómez", "Los Costeños"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Acantilados y playas de Puerto Velero hacia el Caribe.",
        "analisisOrdenPublico": "Acopio temporal de drogas en acantilados; extorsión a operadores turísticos, cabañas y proyectos inmobiliarios de Puerto Velero.",
        "alertasDestacadas": "Extorsión en zona turística de Puerto Velero.",
        "coordinates": {"lat": 10.875, "lng": -74.981}
    },
    {
        "id": "atlantico-galapa",
        "name": "Galapa",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 134,
        "votos": 19739,
        "porcentaje": 71.20,
        "gruposArmados": ["GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Los Costeños", "Los Pepes (Digno Palomino)"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Parque logístico e industrial sobre la vía Cordialidad.",
        "analisisOrdenPublico": "Zona de bodegas utilizada para acopio y dosificación de estupefacientes a gran escala antes de moverlos hacia Barranquilla.",
        "alertasDestacadas": "Uso de bodegas industriales para caletas de droga.",
        "coordinates": {"lat": 10.898, "lng": -74.887}
    },
    {
        "id": "atlantico-malambo",
        "name": "Malambo",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 274,
        "votos": 40114,
        "porcentaje": 73.07,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Sergio Antonio Carrascal Gómez", "Los Costeños", "Los Pepes"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Frontera sobre el río Magdalena y sede del Aeropuerto de Carga.",
        "analisisOrdenPublico": "Infiltración invisible de AGC y tercerización criminal sin patrullajes para no alertar a autoridades metropolitanas. Guerras por microtráfico.",
        "alertasDestacadas": "Vigilancia ilícita sobre infraestructura de transporte aéreo de carga.",
        "coordinates": {"lat": 10.858, "lng": -74.773}
    },
    {
        "id": "atlantico-baranoa",
        "name": "Baranoa",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 158,
        "votos": 23514,
        "porcentaje": 66.72,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Carlos Daniel Fulaye Vargas", "Los Costeños", "Los Pepes"],
        "modalidades": ["Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Centro geográfico del departamento que conecta con el Canal del Dique.",
        "analisisOrdenPublico": "Articulación de planes de expansión portuaria y extorsión por la Subestructura Fulaye Vargas; asedio comercial a tenderos.",
        "alertasDestacadas": "Extorsión a comerciantes céntricos.",
        "coordinates": {"lat": 10.793, "lng": -74.916}
    },
    {
        "id": "atlantico-santotomas",
        "name": "Santo Tomás",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 80,
        "votos": 11140,
        "porcentaje": 66.46,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Carlos Daniel Fulaye Vargas", "Los Costeños", "La Nueva Generación"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Carretera Oriental y accesos al río Magdalena.",
        "analisisOrdenPublico": "Municipio cultural transformado en escenario de asedio extorsivo y atentados sicariales. AGC disputa rutas de microtráfico periféricas.",
        "alertasDestacadas": "Ataques sicariales a locales comerciales.",
        "coordinates": {"lat": 10.758, "lng": -74.757}
    },
    {
        "id": "atlantico-luruaco",
        "name": "Luruaco",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 77,
        "votos": 6915,
        "porcentaje": 50.78,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Carlos Daniel Fulaye Vargas", "Los Costeños", "Los Pepes"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Límite con Bolívar y laguna de Luruaco.",
        "analisisOrdenPublico": "Corredor estratégico hacia el Canal del Dique; abigeato masivo y vendettas de microtráfico en corregimientos como Palmar de Candelaria.",
        "alertasDestacadas": "Hurto y sacrificio ilegal de ganado (abigeato).",
        "coordinates": {"lat": 10.612, "lng": -75.143}
    },
    {
        "id": "atlantico-repelon",
        "name": "Repelón",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 67,
        "votos": 6553,
        "porcentaje": 54.13,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Frente Nicolás Antonio Urango Reyes", "Los Costeños", "Los Pepes"],
        "modalidades": ["Tráfico y Acopio de Armamento", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Ribera del Embalse del Guájaro limítrofe con Bolívar.",
        "analisisOrdenPublico": "Acopio de armas pesadas y drogas en corregimientos como Rotinet y Villa Rosa. Comisiones sicariales expulsadas de Barranquilla migraron hacia Repelón.",
        "alertasDestacadas": "Migración de sicarios urbanos hacia zonas rurales del Guájaro.",
        "coordinates": {"lat": 10.495, "lng": -75.127}
    },

    # BOLÍVAR
    {
        "id": "bolivar-santacatalina",
        "name": "Santa Catalina",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 43,
        "votos": 5675,
        "porcentaje": 74.73,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Nicolás Antonio Urango Reyes", "Los Costeños (franquicias)"],
        "modalidades": ["Extorsión Comercial y Servicios", "Salida Marítima / Lanchas Go-Fast"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Llanura costera con el volcán de lodo del Totumo y playas vírgenes.",
        "analisisOrdenPublico": "Vacunas al turismo del Totumo y comerciantes. Infiltración de bandas satélites desde Barranquilla hacia Galerazamba para controlar el narcomenudeo.",
        "alertasDestacadas": "Extorsión en zona turística del Totumo y Galerazamba.",
        "coordinates": {"lat": 10.608, "lng": -75.291}
    },
    {
        "id": "bolivar-turbaco",
        "name": "Turbaco",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 220,
        "votos": 30272,
        "porcentaje": 66.31,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Nicolás Antonio Urango Reyes"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Bisagra logística sobre la Troncal de Occidente a minutos de Cartagena.",
        "analisisOrdenPublico": "Ocultamiento de cabecillas y estructuras sicariales en condominios residenciales apartados; monopolio de líneas de microtráfico suburbano.",
        "alertasDestacadas": "Refugio de cabecillas en conjuntos campestres cerrados.",
        "coordinates": {"lat": 10.331, "lng": -75.412}
    },
    {
        "id": "bolivar-marialabaja",
        "name": "María la Baja",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 138,
        "votos": 14766,
        "porcentaje": 69.85,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Héroes del Caribe"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Distrito de riego agrícola y represas de Matuya y El Playón.",
        "analisisOrdenPublico": "Extorsión masiva tasada sobre la agroindustria palmicultora, arrocera y ganadera. Ningún gran productor opera sin pagar la vacuna.",
        "alertasDestacadas": "Vacunas forzosas a ingenios arroceros y palmicultores.",
        "coordinates": {"lat": 9.983, "lng": -75.305}
    },
    {
        "id": "bolivar-magangue",
        "name": "Magangué",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 315,
        "votos": 34408,
        "porcentaje": 62.66,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Nicolás Antonio Urango Reyes"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Segundo municipio más poblado de Bolívar y puerto fluvial rey del río Magdalena.",
        "analisisOrdenPublico": "Plataforma de acopio y despacho de cargamentos fluviales de cocaína hacia el Caribe; extorsión de base en el mercado y comercio fluvial.",
        "alertasDestacadas": "Flujo de narcóticos por lanchas en la confluencia de ríos.",
        "coordinates": {"lat": 9.243, "lng": -74.757}
    },
    {
        "id": "bolivar-mompos",
        "name": "Mompós",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 127,
        "votos": 10744,
        "porcentaje": 50.98,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Erlin Pino Duarte"],
        "modalidades": ["Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Distrito Especial en la Depresión Momposina, patrimonio histórico.",
        "analisisOrdenPublico": "Extorsiones silenciosas a joyerías tradicionales de filigrana de oro, operadores hoteleros y contratistas de obras para no ahuyentar el turismo.",
        "alertasDestacadas": "Vacunas a talleres tradicionales de filigrana de oro.",
        "coordinates": {"lat": 9.242, "lng": -74.426}
    },
    {
        "id": "bolivar-montecristo",
        "name": "Montecristo",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 37,
        "votos": 2558,
        "porcentaje": 54.39,
        "gruposArmados": ["ELN", "Clan del Golfo / AGC"],
        "subestructuras": ["ELN Frente Luis José Solano Sepúlveda", "AGC Subestructura Erlin Pino Duarte"],
        "modalidades": ["Minería Ilegal de Oro", "Ataques a Infraestructura", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Estribaciones de la Serranía de San Lucas, rico en vetas de oro.",
        "analisisOrdenPublico": "Crisis humanitaria aguda. El ELN defiende las minas de oro tradicionales contra la ofensiva de expansión del Clan del Golfo y ataca a la Fuerza Pública.",
        "alertasDestacadas": "Hostigamientos armados y minas antipersonal en la Serranía.",
        "coordinates": {"lat": 8.297, "lng": -74.475}
    },

    # SUCRE
    {
        "id": "sucre-palmito",
        "name": "Palmito",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 43,
        "votos": 5847,
        "porcentaje": 64.37,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Corredor rural indígena Zenú entre Córdoba y el Golfo de Morrosquillo.",
        "analisisOrdenPublico": "Ocultamiento de armas y dinero en efectivo en fincas rurales; cobro periódico de cuotas a productores de maíz, yuca y ganaderos.",
        "alertasDestacadas": "Presión sobre la comunidad indígena Zenú.",
        "coordinates": {"lat": 9.336, "lng": -75.549}
    },
    {
        "id": "sucre-toluviejo",
        "name": "Toluviejo",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 68,
        "votos": 8457,
        "porcentaje": 61.46,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Extorsión Comercial y Servicios", "Ataques a Infraestructura"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Canteras de caliza y puerta de entrada hacia los Montes de María.",
        "analisisOrdenPublico": "Extorsión a canteras de piedra caliza, volqueteros y contratistas viales. Constreñimiento a juntas comunales.",
        "alertasDestacadas": "Vacunas a empresas de materiales de construcción.",
        "coordinates": {"lat": 9.452, "lng": -75.438}
    },
    {
        "id": "sucre-coloso",
        "name": "Colosó",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 27,
        "votos": 3237,
        "porcentaje": 59.09,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Confinamiento y Paros Armados", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Montes de María con quebradas y relieve montañoso.",
        "analisisOrdenPublico": "Control social silencioso; cuotas fijas de $600.000 a $1.500.000 a fincas de aguacate y tabaco; refugio tras cometer sicariatos en Sincelejo.",
        "alertasDestacadas": "Tarifas extorsivas fijas impuestas al agro tradicional.",
        "coordinates": {"lat": 9.489, "lng": -75.352}
    },
    {
        "id": "sucre-chalan",
        "name": "Chalán",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 17,
        "votos": 1580,
        "porcentaje": 50.91,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Moderado",
        "posicionGeoestrategica": "Corazón de los Montes de María con topografía escarpada.",
        "analisisOrdenPublico": "Cabecillas operan vestidos de civil debido a golpes militares previos; vacunas a pequeños finqueros y transportadores de tabaco.",
        "alertasDestacadas": "Mimetismo civil de mandos ilegales.",
        "coordinates": {"lat": 9.549, "lng": -75.314}
    },
    {
        "id": "sucre-ovejas",
        "name": "Ovejas",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 74,
        "votos": 9372,
        "porcentaje": 63.47,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Urango Reyes", "Subestructura Manuel José Gaitán"],
        "modalidades": ["Tráfico y Acopio de Armamento", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Capital del tabaco sobre la Troncal de Occidente.",
        "analisisOrdenPublico": "Ruta de enfriamiento de vehículos e insumos hacia El Carmen de Bolívar; informantes en motos reportan movimientos de la Infantería de Marina.",
        "alertasDestacadas": "Red de informantes motorizados en vías principales.",
        "coordinates": {"lat": 9.529, "lng": -75.234}
    },
    {
        "id": "sucre-sampues",
        "name": "Sampués",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 117,
        "votos": 15913,
        "porcentaje": 65.90,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Centro artesanal nacional sobre la Troncal de Occidente.",
        "analisisOrdenPublico": "Cuotas extorsivas a talleres y vitrinas de muebles de madera, mimbre y tejedores de sombrero vueltiao bajo amenazas carcelarias.",
        "alertasDestacadas": "Extorsión al gremio artesano de la caña flecha.",
        "coordinates": {"lat": 9.183, "lng": -75.381}
    },
    {
        "id": "sucre-sanmarcos",
        "name": "San Marcos",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 146,
        "votos": 16242,
        "porcentaje": 71.90,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Uldar Cardona Rueda"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "La 'Perla del San Jorge', despensa agrícola y puerto fluvial de La Mojana.",
        "analisisOrdenPublico": "Presión criminal sobre cosechas y ganado; panfleto propagandístico de falsa tregua desmentido por la Fuerza Pública.",
        "alertasDestacadas": "Falsos anuncios de tregua para bajar denuncias ciudadanas.",
        "coordinates": {"lat": 8.662, "lng": -75.132}
    },

    # CÓRDOBA
    {
        "id": "cordoba-sanbernardo",
        "name": "San Bernardo del Viento",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 92,
        "votos": 10232,
        "porcentaje": 65.89,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Zuley Guerra Castro"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Confinamiento y Paros Armados", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Desembocadura del río Sinú al Mar Caribe.",
        "analisisOrdenPublico": "Puntos ciegos ideales para acopio y despacho de lanchas rápidas go-fast hacia Centroamérica. Regulación estricta de quién entra y sale de manglares.",
        "alertasDestacadas": "Control armado estricto sobre manglares y muelles fluviales.",
        "coordinates": {"lat": 9.354, "lng": -75.952}
    },
    {
        "id": "cordoba-lorica",
        "name": "Lorica",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 279,
        "votos": 34173,
        "porcentaje": 61.23,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Zuley Guerra Castro", "Subestructura Javier Yepes Cantero"],
        "modalidades": ["Extorsión Comercial y Servicios", "Reclutamiento Forzado de Menores"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Capital comercial y de servicios del Bajo Sinú.",
        "analisisOrdenPublico": "Cobro de vacunas en plaza de mercado, porcentaje a prestamistas informales 'gota a gota' y reclutamiento de jóvenes como campaneros.",
        "alertasDestacadas": "Cobro de impuestos ilegales a prestamistas gota a gota.",
        "coordinates": {"lat": 9.239, "lng": -75.814}
    },
    {
        "id": "cordoba-tuchin",
        "name": "Tuchín",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 86,
        "votos": 11745,
        "porcentaje": 64.38,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán", "Subestructura Javier Yepes Cantero"],
        "modalidades": ["Extorsión Comercial y Servicios", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Cuna del sombrero vueltiao y resguardo indígena Zenú de San Andrés.",
        "analisisOrdenPublico": "Extorsión a artesanos y talleres de caña flecha; intento de suplantar la autoridad de la Guardia Indígena Zenú con amenazas a líderes.",
        "alertasDestacadas": "Coerción a autoridades de la Guardia Indígena Zenú.",
        "coordinates": {"lat": 9.186, "lng": -75.561}
    },
    {
        "id": "cordoba-cerete",
        "name": "Cereté",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 230,
        "votos": 34007,
        "porcentaje": 63.86,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Javier Yepes Cantero"],
        "modalidades": ["Extorsión Comercial y Servicios", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Nodo agroindustrial de arroz, maíz y algodón contiguo a Montería.",
        "analisisOrdenPublico": "Extorsión altamente coordinada a empresas distribuidoras nacionales (Bavaria, Postobón), consorcios viales y reclutamiento de jóvenes en barrios populares.",
        "alertasDestacadas": "Vacunas a distribuidoras nacionales de bebidas y alimentos.",
        "coordinates": {"lat": 8.884, "lng": -75.792}
    },
    {
        "id": "cordoba-montelibano",
        "name": "Montelíbano",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 178,
        "votos": 28685,
        "porcentaje": 75.28,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Rubén Darío Ávila", "Subestructura Javier Yepes Cantero"],
        "modalidades": ["Minería Ilegal de Oro", "Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Mayor centro urbano del San Jorge y enlace con enclaves de níquel y oro.",
        "analisisOrdenPublico": "Votación del 75.28%. Control de corredores entre zonas de producción de coca del sur de Córdoba y rutas nacionales; sicariato urbano y extorsión minera.",
        "alertasDestacadas": "Monopolio sobre insumos químicos y corredores hacia Paramillo.",
        "coordinates": {"lat": 7.979, "lng": -75.621}
    },
    {
        "id": "cordoba-valencia",
        "name": "Valencia",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 90,
        "votos": 7983,
        "porcentaje": 50.21,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Rubén Darío Ávila"],
        "modalidades": ["Tráfico y Acopio de Armamento", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Límite directo con el Urabá antioqueño (San Pedro de Urabá, Apartadó).",
        "analisisOrdenPublico": "Paso obligado de la pasta base producida en Paramillo hacia las terminales de exportación marítima en el Urabá; ingreso de armas y municiones.",
        "alertasDestacadas": "Corredor interdepartamental de tráfico de armas pesadas.",
        "coordinates": {"lat": 8.258, "lng": -76.151}
    },

    # CHOCÓ
    {
        "id": "choco-riosucio",
        "name": "Riosucio",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 52,
        "votos": 6393,
        "porcentaje": 85.70,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Jhon Fredy Orejuela", "ELN Frente Occidental"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Bajo Atrato y ríos Truandó y Salaquí, acceso a selva del Darién.",
        "analisisOrdenPublico": "85.70% de votos. Peajes a lanchas comunitarias y madereros; campos minados defensivos en trochas de acceso; confinamiento de comunidades afro e indígenas.",
        "alertasDestacadas": "Campos minados en trochas de acceso y confinamiento fluvial.",
        "coordinates": {"lat": 7.441, "lng": -77.116}
    },
    {
        "id": "choco-jurado",
        "name": "Juradó",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 13,
        "votos": 1514,
        "porcentaje": 88.38,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Efrén Vargas Gutiérrez", "ELN Compañía Néstor Tulio Durán"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Litoral norte del Pacífico colindante con la frontera panameña.",
        "analisisOrdenPublico": "88.38% de votación. El ELN intercepta lanchas de transporte público secuestrando personas; evacuaciones humanitarias de emergencia por la Armada ante amenazas de muerte directas.",
        "alertasDestacadas": "Evacuaciones de emergencia de comunidades étnicas por la Armada.",
        "coordinates": {"lat": 7.106, "lng": -77.766}
    },
    {
        "id": "choco-bahiasolano",
        "name": "Bahía Solano",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 29,
        "votos": 3860,
        "porcentaje": 80.11,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Jhon Fredy Orejuela", "ELN Compañía Néstor Tulio Durán"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Destino internacional de avistamiento de ballenas en el Pacífico Norte.",
        "analisisOrdenPublico": "80.11% de apoyo. Caletas masivas de cocaína en la selva costera y vacunas a hoteles y operadores turísticos, combinando violencia con desastres naturales.",
        "alertasDestacadas": "Extorsión al sector hotelero y caletas costeras de estupefacientes.",
        "coordinates": {"lat": 6.220, "lng": -77.404}
    },
    {
        "id": "choco-nuqui",
        "name": "Nuquí",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 24,
        "votos": 3250,
        "porcentaje": 89.60,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Jhon Fredy Orejuela", "ELN Frente de Guerra Occidental"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Paraíso ecoturístico en el Golfo de Tribugá.",
        "analisisOrdenPublico": "89.60% de votación. Choques armados directos en esteros y playas; el ELN bloquea lanchas con víveres acusando a comunidades de colaborar con AGC.",
        "alertasDestacadas": "Bloqueo de alimentos por vía marítima a comunidades costeras.",
        "coordinates": {"lat": 5.713, "lng": -77.271}
    },
    {
        "id": "choco-tado",
        "name": "Tadó",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 49,
        "votos": 6002,
        "porcentaje": 78.89,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Jhon Fredy Orejuela", "ELN Frente Ernesto Che Guevara"],
        "modalidades": ["Minería Ilegal de Oro", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Frontera vial hacia Risaralda y cuenca alta del San Juan.",
        "analisisOrdenPublico": "Infiltración de células sicariales de AGC desde Las Ánimas contra el ELN; extorsión directa a los entables de minería de oro aluvial.",
        "alertasDestacadas": "Disputa por las cuencas mineras de oro aluvial.",
        "coordinates": {"lat": 5.267, "lng": -76.559}
    },
    {
        "id": "choco-condoto",
        "name": "Condoto",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 42,
        "votos": 4964,
        "porcentaje": 83.96,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Jhon Fredy Orejuela", "ELN Frente Ernesto Che Guevara"],
        "modalidades": ["Minería Ilegal de Oro", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Capital Platinífera de Colombia en las cuencas de los ríos Condoto e Iró.",
        "analisisOrdenPublico": "83.96% de votación. Vacunas a prenderías y compradores de platino y oro; atentados a bala contra locales comerciales e impuestos a maquinaria pesada.",
        "alertasDestacadas": "Vacunas al comercio formal de platino y metales preciosos.",
        "coordinates": {"lat": 5.094, "lng": -76.650}
    },
    {
        "id": "choco-bajobaudo",
        "name": "Bajo Baudó",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 43,
        "votos": 4491,
        "porcentaje": 90.03,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Baudó", "ELN Frente Ernesto Che Guevara"],
        "modalidades": ["Confinamiento y Paros Armados", "Salida Marítima / Lanchas Go-Fast"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Desembocadura del río Baudó en Pizarro frente a mar abierto.",
        "analisisOrdenPublico": "90.03% de sufragios. Paros armados cruentos del ELN que confinaron a más de 6.800 afrodescendientes e indígenas dejándolos sin alimentos ni agua.",
        "alertasDestacadas": "Confinamiento masivo de más de 6.800 personas.",
        "coordinates": {"lat": 4.954, "lng": -77.366}
    },
    {
        "id": "choco-litoraldelsanjuan",
        "name": "El Litoral de San Juan",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 43,
        "votos": 5343,
        "porcentaje": 98.18,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Jhon Fredy Orejuela", "ELN Frente Ernesto Che Guevara"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Confinamiento y Paros Armados", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Salida al Pacífico hacia las rutas de Buenaventura, esteros y bocanas.",
        "analisisOrdenPublico": "Votación máxima del 98.18%. Despliegue de sicarios fluviales por AGC para expulsar al ELN; combates intensos en esteros y manglares.",
        "alertasDestacadas": "Votación récord (98.18%) en zona de confrontación naval y de manglares.",
        "coordinates": {"lat": 4.269, "lng": -77.369}
    },

    # VALLE DEL CAUCA
    {
        "id": "valle-zarzal",
        "name": "Zarzal",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 120,
        "votos": 16180,
        "porcentaje": 66.66,
        "gruposArmados": ["GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)", "Clan del Golfo / AGC"],
        "subestructuras": ["Los Flacos", "AGC Bloque Pacífico"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Epicentro de transporte de la Troncal de Occidente en el norte del Valle.",
        "analisisOrdenPublico": "Guerra urbana entre Los Flacos y células del Bloque Pacífico de AGC por el narcomenudeo y vacunas a ingenios azucareros y transportadores.",
        "alertasDestacadas": "Oficinas de cobro y vendettas urbanas de Los Flacos.",
        "coordinates": {"lat": 4.398, "lng": -76.074}
    },
    {
        "id": "valle-buga",
        "name": "Buga",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 339,
        "votos": 44607,
        "porcentaje": 63.79,
        "gruposArmados": ["GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)", "Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["La Inmaculada", "Los Magos", "Frente Adán Izquierdo"],
        "modalidades": ["Extorsión Comercial y Servicios", "Reclutamiento Forzado de Menores"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Ciudad turística religiosa y nodo vial central del Valle.",
        "analisisOrdenPublico": "Guerra a sangre y fuego entre bandas locales (Los Magos) y La Inmaculada que causa homicidios múltiples. El Frente Adán Izquierdo recluta adolescentes en veredas.",
        "alertasDestacadas": "Masacres urbanas por control de puntos de expendio.",
        "coordinates": {"lat": 3.901, "lng": -76.298}
    },
    {
        "id": "valle-yotoco",
        "name": "Yotoco",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 51,
        "votos": 5808,
        "porcentaje": 61.56,
        "gruposArmados": ["GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)", "Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Los Sapitos", "Frente Adán Izquierdo"],
        "modalidades": ["Reclutamiento Forzado de Menores", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Corredor estratégico de Mediacanoa hacia Buenaventura y Eje Cafetero.",
        "analisisOrdenPublico": "Los Sapitos perfilaban escolares en redes sociales para microtráfico; Frente Adán Izquierdo cobra vacunas agrícolas y custodia cargamentos de droga.",
        "alertasDestacadas": "Instrumentalización de menores en entornos escolares.",
        "coordinates": {"lat": 3.864, "lng": -76.384}
    },
    {
        "id": "valle-calima",
        "name": "Calima (El Darién)",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 54,
        "votos": 4802,
        "porcentaje": 50.76,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["Frente Jaime Martínez", "Frente Adán Izquierdo", "Frente 57 Yair Bermúdez"],
        "modalidades": ["Extorsión Comercial y Servicios", "Confinamiento y Paros Armados", "Minería Ilegal de Oro"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Lago Calima y Parque Natural Páramo del Duende hacia el Pacífico.",
        "analisisOrdenPublico": "Retenes ilegales con carnetización forzada; videos intimidatorios contra hoteles y fincas turísticas del Lago Calima; caletas con fusiles en el páramo.",
        "alertasDestacadas": "Extorsión al sector hotelero y turístico del Lago Calima.",
        "coordinates": {"lat": 3.931, "lng": -76.488}
    },
    {
        "id": "valle-pradera",
        "name": "Pradera",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 132,
        "votos": 19477,
        "porcentaje": 75.26,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["Frente Adán Izquierdo", "Frente Dagoberto Ramos", "Frente 57 Yair Bermúdez"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Reclutamiento Forzado de Menores", "Ataques a Infraestructura"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Corredor de alta montaña hacia Tolima (Cañón de Las Hermosas).",
        "analisisOrdenPublico": "Vacunas por hectárea a ingenios azucareros y ganaderos; vehículos bomba contra subestaciones de policía en límites y reclutamiento infantil.",
        "alertasDestacadas": "Vehículos con explosivos y reclutamiento en escuelas rurales.",
        "coordinates": {"lat": 3.421, "lng": -76.244}
    },
    {
        "id": "valle-florida",
        "name": "Florida",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 164,
        "votos": 27141,
        "porcentaje": 77.63,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["Frente Dagoberto Ramos", "Frente 57 Yair Bermúdez"],
        "modalidades": ["Ataques a Infraestructura", "Extorsión Agropecuaria y Ganadera", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Límite directo con Miranda y Corinto (Cauca).",
        "analisisOrdenPublico": "Control militar real en zona alta por la Dagoberto Ramos; cierre de vías hacia Miranda por combates con el Ejército; quema de maquinaria de ingenios azucareros.",
        "alertasDestacadas": "Quema de maquinaria pesada de ingenios azucareros.",
        "coordinates": {"lat": 3.322, "lng": -76.234}
    },
    {
        "id": "valle-candelaria",
        "name": "Candelaria",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 262,
        "votos": 43650,
        "porcentaje": 74.12,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["Frente Dagoberto Ramos", "Frente 57 Yair Bermúdez"],
        "modalidades": ["Uso de Drones con Explosivos", "Ataques a Infraestructura"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "A 15 minutos de Cali, conectado por el puente de Juanchito.",
        "analisisOrdenPublico": "Despliegue de drones kamikaze con explosivos desde la periferia rural al no poder ingresar camiones bomba por controles del Ejército.",
        "alertasDestacadas": "Uso de drones kamikaze para atacar objetivos estratégicos.",
        "coordinates": {"lat": 3.407, "lng": -76.350}
    },

    # CAUCA
    {
        "id": "cauca-puertotejada",
        "name": "Puerto Tejada",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 104,
        "votos": 20343,
        "porcentaje": 86.06,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Dagoberto Ramos", "27 Pandillas urbanas activas (500 jóvenes)"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Noreste del Cauca conectado con el área metropolitana de Cali.",
        "analisisOrdenPublico": "86.06% de votación. Más de 27 pandillas activas armadas por la Dagoberto Ramos para distribuir marihuana y proteger caletas; quema de maquinaria de ingenios.",
        "alertasDestacadas": "27 pandillas urbanas instrumentalizadas por el narcotráfico.",
        "coordinates": {"lat": 3.231, "lng": -76.417}
    },
    {
        "id": "cauca-miranda",
        "name": "Miranda",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 70,
        "votos": 12996,
        "porcentaje": 80.01,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["Frente Dagoberto Ramos (Comisión Santiago Díaz)", "Frente 57 Yair Bermúdez"],
        "modalidades": ["Ataques a Infraestructura", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Corazón histórico de la insurgencia en el norte del Cauca.",
        "analisisOrdenPublico": "Ataques con ráfagas de fusil en motos vestidos de civil contra la estación de policía; incursiones de exterminio sicarial por el Frente 57.",
        "alertasDestacadas": "Ataques diarios de hostigamiento a la estación policial.",
        "coordinates": {"lat": 3.251, "lng": -76.227}
    },
    {
        "id": "cauca-padilla",
        "name": "Padilla",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 24,
        "votos": 3659,
        "porcentaje": 79.94,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Dagoberto Ramos"],
        "modalidades": ["Uso de Drones con Explosivos", "Ataques a Infraestructura"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Llanura plana con vías secundarias hacia Miranda y Corinto.",
        "analisisOrdenPublico": "Uso de locales comerciales civiles como trinchera de tiro contra la policía; vehículos bomba y drones explosivos acondicionados para ataques asimétricos.",
        "alertasDestacadas": "Uso de civiles y locales comerciales como escudos humanos.",
        "coordinates": {"lat": 3.218, "lng": -76.313}
    },
    {
        "id": "cauca-villarica",
        "name": "Villa Rica",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 46,
        "votos": 9556,
        "porcentaje": 88.17,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Dagoberto Ramos"],
        "modalidades": ["Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Planicie cañera sobre la vía Panamericana.",
        "analisisOrdenPublico": "Red de talleres clandestinos dedicados a fabricar caletas de doble fondo en furgones para transportar marihuana hacia Cali y Buenaventura.",
        "alertasDestacadas": "Talleres clandestinos de caletas en vehículos de carga.",
        "coordinates": {"lat": 3.183, "lng": -76.483}
    },
    {
        "id": "cauca-guachene",
        "name": "Guachené",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 47,
        "votos": 9076,
        "porcentaje": 83.48,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Dagoberto Ramos"],
        "modalidades": ["Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Conexión plana hacia la Panamericana.",
        "analisisOrdenPublico": "Simbiosis entre GAOr y pandillas urbanas con picos de hasta 49 homicidios anuales y masacres de civiles.",
        "alertasDestacadas": "Picos drásticos de homicidios y masacres comunitarias.",
        "coordinates": {"lat": 3.136, "lng": -76.392}
    },
    {
        "id": "cauca-suarez",
        "name": "Suárez",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 62,
        "votos": 9318,
        "porcentaje": 69.58,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Segunda Marquetalia"],
        "subestructuras": ["Frente Jaime Martínez", "Estructura Diomer Cortés"],
        "modalidades": ["Uso de Drones con Explosivos", "Confinamiento y Paros Armados", "Ataques a Infraestructura"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Represa de Salvajina y cuenca del río Naya hacia el Pacífico.",
        "analisisOrdenPublico": "Lanzamiento de explosivos teledirigidos contra garitas policiales; confinamiento forzado de alumnos y docentes en escuelas para usarlos de escudo.",
        "alertasDestacadas": "Confinamiento de colegios y escuelas como escudos de guerra.",
        "coordinates": {"lat": 2.954, "lng": -76.696}
    },
    {
        "id": "cauca-morales",
        "name": "Morales",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 75,
        "votos": 12333,
        "porcentaje": 70.83,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Jaime Martínez"],
        "modalidades": ["Uso de Drones con Explosivos", "Minería Ilegal de Oro"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Paso entre Panamericana y la cordillera hacia el Cañón del Micay.",
        "analisisOrdenPublico": "Ataques sistemáticos con enjambres de drones modificados con explosivos (AEI) y minería ilegal de oro en cuencas de la cordillera.",
        "alertasDestacadas": "Enjambres de drones para soltar explosivos sobre la población.",
        "coordinates": {"lat": 2.759, "lng": -76.618}
    },
    {
        "id": "cauca-cajibio",
        "name": "Cajibío",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 83,
        "votos": 13051,
        "porcentaje": 67.41,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Jaime Martínez (Taller de drones)"],
        "modalidades": ["Uso de Drones con Explosivos", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Corredor hacia el Cañón del Micay.",
        "analisisOrdenPublico": "Célula técnica especializada en modificación de drones. Tácticas de tierra arrasada en corregimiento Ortega: quema de casas campesinas y asesinatos de líderes sociales.",
        "alertasDestacadas": "Tierra arrasada con quema de viviendas de campesinos.",
        "coordinates": {"lat": 2.607, "lng": -76.564}
    },
    {
        "id": "cauca-piendamo",
        "name": "Piendamó",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 102,
        "votos": 13317,
        "porcentaje": 61.47,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN"],
        "subestructuras": ["Frente Jaime Martínez", "ELN Frente Manuel Vásquez Castaño"],
        "modalidades": ["Ataques a Infraestructura", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Cordón umbilical de la Vía Panamericana entre Popayán y Cali.",
        "analisisOrdenPublico": "Motos bomba a control remoto en sector comercial; ELN quema maquinaria agrícola en Tunía y promueve invasiones de tierras.",
        "alertasDestacadas": "Motocicletas bomba a control remoto en cascos urbanos.",
        "coordinates": {"lat": 2.641, "lng": -76.529}
    },
    {
        "id": "cauca-popayan",
        "name": "Popayán",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 785,
        "votos": 128296,
        "porcentaje": 64.80,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN"],
        "subestructuras": ["Frente Jaime Martínez", "ELN Frente Manuel Vásquez Castaño"],
        "modalidades": ["Ataques a Infraestructura", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Capital departamental del Cauca.",
        "analisisOrdenPublico": "Estrategia de asfixia urbana. Atentados con explosivos a plantas industriales (Postobón) por el ELN; falsos retenes con uniformes en salidas hacia El Tambo y Rosas.",
        "alertasDestacadas": "Atentados con explosivos a sedes empresariales en la capital.",
        "coordinates": {"lat": 2.444, "lng": -76.614}
    },
    {
        "id": "cauca-lopezdemicay",
        "name": "López de Micay",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 61,
        "votos": 7871,
        "porcentaje": 92.28,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN"],
        "subestructuras": ["Frente Jaime Martínez", "ELN Frente Ernesto Che Guevara"],
        "modalidades": ["Minería Ilegal de Oro", "Confinamiento y Paros Armados", "Salida Marítima / Lanchas Go-Fast"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Corredor del Cañón del Micay hasta el Océano Pacífico.",
        "analisisOrdenPublico": "92.28% de votos. Campamentos atrincherados con antenas satelitales; desvío de toneladas de oro en cuencas de ríos y desplazamiento masivo de 75 familias por combates con el ELN.",
        "alertasDestacadas": "Campamentos con internet satelital y zanjas de arrastre.",
        "coordinates": {"lat": 2.825, "lng": -77.241}
    },
    {
        "id": "cauca-timbiqui",
        "name": "Timbiquí",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 60,
        "votos": 10101,
        "porcentaje": 97.39,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN"],
        "subestructuras": ["Frente Rafael Aguilera (Jhonier Toro Arenas)", "ELN Frente Ernesto Che Guevara"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Minería Ilegal de Oro", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Cuenca del río Timbiquí y manglares del Pacífico.",
        "analisisOrdenPublico": "Votación masiva del 97.39%. Artefactos explosivos fluviales y coches bomba; siembra de explosivos en los ríos para impedir el avance de embarcaciones.",
        "alertasDestacadas": "Siembra de artefactos explosivos sobre el lecho de los ríos.",
        "coordinates": {"lat": 2.772, "lng": -77.663}
    },
    {
        "id": "cauca-patia",
        "name": "Patía",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 95,
        "votos": 15757,
        "porcentaje": 77.41,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN", "Segunda Marquetalia"],
        "subestructuras": ["Frente Carlos Patiño", "ELN Frente Manuel Vásquez Castaño", "Segunda Marquetalia Estructura Diomer Cortés"],
        "modalidades": ["Ataques a Infraestructura", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Valle plano por donde cruza el tramo más vulnerable de la Panamericana.",
        "analisisOrdenPublico": "Abandono de explosivos sobre la Panamericana; combates cuerpo a cuerpo en el corredor hacia Balboa paralizando transporte intermunicipal.",
        "alertasDestacadas": "Cierre forzado de la Vía Panamericana por combates.",
        "coordinates": {"lat": 2.068, "lng": -77.054}
    },

    # NARIÑO
    {
        "id": "narino-elcharco",
        "name": "El Charco",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 60,
        "votos": 9777,
        "porcentaje": 92.79,
        "gruposArmados": ["Segunda Marquetalia", "Comuneros del Sur / AUN"],
        "subestructuras": ["Frente Oliver Sinisterra", "Estructura Los Contadores", "Compañía Cimarrón"],
        "modalidades": ["Reclutamiento Forzado de Menores", "Minería Ilegal de Oro", "Salida Marítima / Lanchas Go-Fast"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Río Tapaje y salida al océano en el norte de Nariño.",
        "analisisOrdenPublico": "Votación del 92.79%. Reclutamiento forzado de niños para transporte de explosivos; choques violentos por el control de dragas de oro en ríos limítrofes.",
        "alertasDestacadas": "Reclutamiento de menores para transporte de explosivos.",
        "coordinates": {"lat": 2.477, "lng": -78.110}
    },
    {
        "id": "narino-olayaherrera",
        "name": "Olaya Herrera",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 53,
        "votos": 8401,
        "porcentaje": 93.91,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Segunda Marquetalia"],
        "subestructuras": ["Frente Rafael Aguilera", "Frente Franco Benavides", "Segunda Marquetalia Allende Perilla"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Confinamiento y Paros Armados", "Salida Marítima / Lanchas Go-Fast"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Cuenca del río Satinga hacia el Pacífico.",
        "analisisOrdenPublico": "93.91% de votos. Complejos cristalizaderos capaces de producir toneladas mensuales; control de muelles informales en Bocas de Satinga tasando alimentos.",
        "alertasDestacadas": "Impuestos delictivos obligatorios a todos los víveres.",
        "coordinates": {"lat": 2.348, "lng": -78.324}
    },
    {
        "id": "narino-mosquera",
        "name": "Mosquera",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 27,
        "votos": 4065,
        "porcentaje": 97.97,
        "gruposArmados": ["Segunda Marquetalia", "Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Estructura Alfonso Cano", "Estructura Alan Rodríguez"],
        "modalidades": ["Semisumergibles", "Salida Marítima / Lanchas Go-Fast"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Archipiélago de manglares sobre el océano Pacífico nariñense.",
        "analisisOrdenPublico": "Votación del 97.97%. Astilleros artesanales clandestinos para ensamblar semisumergibles nocturnos guiados por prácticos locales que burlan guardacostas.",
        "alertasDestacadas": "Astilleros clandestinos de artefactos navales semisumergibles.",
        "coordinates": {"lat": 2.508, "lng": -78.451}
    },
    {
        "id": "narino-franciscopizarro",
        "name": "Francisco Pizarro (Salahonda)",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 26,
        "votos": 4009,
        "porcentaje": 96.53,
        "gruposArmados": ["Segunda Marquetalia", "Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Estructura Alfonso Cano", "Estructura Alan Rodríguez"],
        "modalidades": ["Semisumergibles", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Desembocadura de los ríos Patía y Tapaje al mar abierto.",
        "analisisOrdenPublico": "96.53% de votos. Balaceras continuas en lanchas rápidas por bocanas; comunidades de Salahonda confinadas e incomunicadas sin provisiones.",
        "alertasDestacadas": "Bloqueo total del transporte marítimo y desabastecimiento.",
        "coordinates": {"lat": 2.062, "lng": -78.653}
    },
    {
        "id": "narino-maguipayan",
        "name": "Magüí Payán",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 31,
        "votos": 4711,
        "porcentaje": 97.59,
        "gruposArmados": ["Segunda Marquetalia"],
        "subestructuras": ["Frente Oliver Sinisterra", "Estructura Alfonso Cano", "Frente Iván Ríos"],
        "modalidades": ["Confinamiento y Paros Armados", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Tercer eje del Triángulo de Telembí sobre el río Magüí.",
        "analisisOrdenPublico": "Votación del 97.59%. Compra forzada de pasta base en laboratorios selváticos; combates ribereños obligan a abandonar veredas enteras.",
        "alertasDestacadas": "Éxodo masivo de comunidades ribereñas atrapadas en fuego cruzado.",
        "coordinates": {"lat": 1.733, "lng": -78.026}
    },
    {
        "id": "narino-ipiales",
        "name": "Ipiales",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 300,
        "votos": 48510,
        "porcentaje": 71.85,
        "gruposArmados": ["Comandos de Frontera (CDF)", "Comuneros del Sur / AUN"],
        "subestructuras": ["Comandos de Frontera", "Milicias Comuneros del Sur"],
        "modalidades": ["Tráfico y Acopio de Armamento", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Puerto terrestre binacional más importante entre Colombia y Ecuador (Rumichaca).",
        "analisisOrdenPublico": "Guerra silenciosa sin frentes uniformados. Flujo masivo de cocaína por trochas hacia Ecuador y retorno de armas y dólares en efectivo.",
        "alertasDestacadas": "Tráfico fronterizo de divisas y armamento hacia Ecuador.",
        "coordinates": {"lat": 0.828, "lng": -77.643}
    },
    {
        "id": "narino-samaniengo",
        "name": "Samaniego",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 81,
        "votos": 14289,
        "porcentaje": 85.45,
        "gruposArmados": ["Comuneros del Sur / AUN", "Disidencias FARC (Iván Mordisco / EMC)", "Segunda Marquetalia"],
        "subestructuras": ["Compañía Jaime Toño Obando", "Frente Franco Benavides", "Frente Iván Ríos"],
        "modalidades": ["Uso de Drones con Explosivos", "Minería Ilegal de Oro"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Punto de enlace entre cordillera aurífera y enclaves cocaleros.",
        "analisisOrdenPublico": "85.45% de apoyo. Drones con explosivos contra patrullas del Ejército en el cañón del río Guáitara; milicias urbanas cometen homicidios selectivos.",
        "alertasDestacadas": "Uso intensivo de drones explosivos en el cañón del Guáitara.",
        "coordinates": {"lat": 1.336, "lng": -77.595}
    },

    # AMAZONÍA & ORINOQUÍA
    {
        "id": "putumayo-sanmiguel",
        "name": "San Miguel",
        "department": "Putumayo",
        "departmentSlug": "putumayo",
        "region": "Amazonía-Orinoquía",
        "mesas": 51,
        "votos": 8355,
        "porcentaje": 87.40,
        "gruposArmados": ["Comandos de Frontera (CDF)"],
        "subestructuras": ["Comandos de Frontera"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Frontera sobre el río San Miguel conectando con Sucumbíos (Ecuador).",
        "analisisOrdenPublico": "Corredor directo con la economía dolarizada de Ecuador. Tráfico de químicos y armas de contrabando; empleo de drones térmicos para burlar patrullajes fluviales.",
        "alertasDestacadas": "Drones térmicos para coordinar tráfico nocturno fluvial.",
        "coordinates": {"lat": 0.344, "lng": -76.911}
    },
    {
        "id": "putumayo-puertoleguizamo",
        "name": "Puerto Leguízamo",
        "department": "Putumayo",
        "departmentSlug": "putumayo",
        "region": "Amazonía-Orinoquía",
        "mesas": 50,
        "votos": 4068,
        "porcentaje": 62.05,
        "gruposArmados": ["Comandos de Frontera (CDF)", "Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Comandos de Frontera", "Frente Carolina Ramírez"],
        "modalidades": ["Reclutamiento Forzado de Menores", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Confluencia de los ríos Caquetá y Putumayo, frontera con Perú.",
        "analisisOrdenPublico": "Guerra abierta de selva profunda. Incursiones en comunidades indígenas para reclutamiento forzoso de niños y extorsión a barcazas de transporte fluvial hacia Caquetá y Amazonas.",
        "alertasDestacadas": "Reclutamiento forzado en resguardos indígenas ribereños.",
        "coordinates": {"lat": -0.194, "lng": -74.781}
    },
    {
        "id": "vaupes-caruru",
        "name": "Carurú",
        "department": "Vaupés",
        "departmentSlug": "vaupes",
        "region": "Amazonía-Orinoquía",
        "mesas": 6,
        "votos": 653,
        "porcentaje": 85.35,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Armando Ríos"],
        "modalidades": ["Reclutamiento Forzado de Menores", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Frontera selvática con el Guaviare a través de caños vírgenes.",
        "analisisOrdenPublico": "85.35% de votos. Reclutamiento sistemático en internados y escuelas indígenas; asesinatos de padres que intentan esconder o ayudar a escapar a sus hijos.",
        "alertasDestacadas": "Asesinatos de padres que resisten el reclutamiento infantil.",
        "coordinates": {"lat": 1.025, "lng": -71.300}
    },
    {
        "id": "vaupes-taraira",
        "name": "Taraira",
        "department": "Vaupés",
        "departmentSlug": "vaupes",
        "region": "Amazonía-Orinoquía",
        "mesas": 6,
        "votos": 341,
        "porcentaje": 73.33,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["Frente Carolina Ramírez", "Frente Rafael Aguilera", "Bloque Jorge Suárez Briceño"],
        "modalidades": ["Confinamiento y Paros Armados", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Límite meridional del Vaupés con la cuenca del río Apaporis y Brasil.",
        "analisisOrdenPublico": "Autopista fluvial hacia Brasil; expulsión de comunidades indígenas del río Apaporis hacia el casco urbano por combates entre frentes disidentes.",
        "alertasDestacadas": "Éxodo de indígenas del río Apaporis hacia el casco urbano.",
        "coordinates": {"lat": -0.551, "lng": -69.645}
    },
    {
        "id": "guainia-barrancominas",
        "name": "Barrancominas",
        "department": "Guainía",
        "departmentSlug": "guainia",
        "region": "Amazonía-Orinoquía",
        "mesas": 18,
        "votos": 2294,
        "porcentaje": 91.65,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["Frente Armando Ríos", "Bloque Jorge Suárez Briceño"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Puerto estratégico sobre el río Guaviare que une Guaviare, Vichada y Guainía.",
        "analisisOrdenPublico": "Votación del 91.65%. Embudo logístico donde se requisan todas las embarcaciones de carga civil y motores fuera de borda; acopio clandestino de combustible y plantas eléctricas.",
        "alertasDestacadas": "Retenes armados en las curvas ciegas del río Guaviare.",
        "coordinates": {"lat": 3.964, "lng": -69.791}
    },
    {
        "id": "sanandres-providencia",
        "name": "Providencia",
        "department": "San Andrés y Providencia",
        "departmentSlug": "san-andres",
        "region": "Insular",
        "mesas": 14,
        "votos": 1088,
        "porcentaje": 59.03,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Células satélites AGC", "Redes urbanas insulares"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast"],
        "nivelRiesgo": "Moderado",
        "posicionGeoestrategica": "Isla septentrional a 230 km de costas centroamericanas.",
        "analisisOrdenPublico": "Aduana marítima para acopio de combustible de lanchas rápidas en cayos exteriores rumbo a Honduras o Nicaragua.",
        "alertasDestacadas": "Puntos de reabastecimiento marítimo en aguas abiertas.",
        "coordinates": {"lat": 13.348, "lng": -81.370}
    }
]

for rec in more_records:
    existing[rec["id"]] = rec

all_list = list(existing.values())

with open("src/data/municipalities.json", "w", encoding="utf-8") as f:
    json.dump(all_list, f, ensure_ascii=False, indent=2)

with open("public/data/municipalities.json", "w", encoding="utf-8") as f:
    json.dump(all_list, f, ensure_ascii=False, indent=2)

print(f"Total structured municipalities in dossier: {len(all_list)}")
