#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
import os

# Data representing the document pages and geopolitical analysis
records = [
    # LA GUAJIRA
    {
        "id": "guajira-uribia",
        "name": "Uribia",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 385,
        "votos": 22343,
        "porcentaje": 60.85,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["Los Pachenca / Alias Naín Pérez", "Subestructura AGC Alta Guajira"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Extremo norte peninsular con extensos muelles naturales y pistas clandestinas hacia el Caribe.",
        "analisisOrdenPublico": "Disputa frontal entre ACSN (Los Pachenca) y el Clan del Golfo (AGC) por el control de la salida de cargamentos de estupefacientes y el ingreso de contrabando en la Alta Guajira.",
        "alertasDestacadas": "Corredores de narcotráfico marítimo hacia las Antillas.",
        "coordinates": {"lat": 11.7139, "lng": -72.2658}
    },
    {
        "id": "guajira-manaure",
        "name": "Manaure",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 190,
        "votos": 24216,
        "porcentaje": 68.26,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["ACSN Los Pachenca", "Estructura AGC Costa Norte"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Zona costera salinera con amplio litoral para embarque clandestino.",
        "analisisOrdenPublico": "Presencia de ACSN intentando expandir capacidades logísticas; disputa con el Clan del Golfo por el control de las costas y rutas de contrabando y narcotráfico.",
        "alertasDestacadas": "Monitoreo por uso de costas desiertas para tráfico.",
        "coordinates": {"lat": 11.775, "lng": -72.444}
    },
    {
        "id": "guajira-maicao",
        "name": "Maicao",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 401,
        "votos": 35313,
        "porcentaje": 58.84,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["ACSN Los Pachenca", "Subestructura AGC Frontera"],
        "modalidades": ["Tráfico y Acopio de Armamento", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Principal nodo fronterizo comercial con Venezuela (Paraguachón).",
        "analisisOrdenPublico": "Replicación de dinámicas delictivas de Uribia; corredor de alto valor estratégico para contrabando, armas y narcotráfico en disputa entre ACSN y AGC.",
        "alertasDestacadas": "Extorsión en zonas comerciales céntricas y pasos de trocha.",
        "coordinates": {"lat": 11.378, "lng": -72.241}
    },
    {
        "id": "guajira-albania",
        "name": "Albania",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 65,
        "votos": 8913,
        "porcentaje": 74.85,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)", "ELN"],
        "subestructuras": ["ACSN Los Pachenca", "Frente de Guerra Norte ELN", "AGC"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Entorno del complejo carbonífero de Cerrejón y piedemonte de Perijá.",
        "analisisOrdenPublico": "Expansión de ACSN hacia el sur; disputa de rutas con AGC y presencia intermitente del ELN proveniente de la Serranía del Perijá.",
        "alertasDestacadas": "Injerencia armada en el corredor minero.",
        "coordinates": {"lat": 11.161, "lng": -72.592}
    },
    {
        "id": "guajira-riohacha",
        "name": "Riohacha",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 471,
        "votos": 50857,
        "porcentaje": 60.03,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["ACSN Troncal del Caribe", "AGC Comisiones Urbanas"],
        "modalidades": ["Extorsión Comercial y Servicios", "Salida Marítima / Lanchas Go-Fast", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Capital departamental, puerto marítimo y eje sobre la Troncal del Caribe.",
        "analisisOrdenPublico": "Guerra abierta y frontal por el control definitivo de la capital. Fuerte arraigo histórico de ACSN (extorsión, microtráfico y sicariato) frente a incursión de AGC desde el sur.",
        "alertasDestacadas": "Ola de sicariato y extorsión sistemática a comerciantes.",
        "coordinates": {"lat": 11.544, "lng": -72.907}
    },
    {
        "id": "guajira-barrancas",
        "name": "Barrancas",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 82,
        "votos": 10839,
        "porcentaje": 69.66,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Francisco José Morelo Peñate", "Subestructura Rufino José Morales", "ACSN"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Corredor vial entre el Cesar y Maicao en la zona carbonífera.",
        "analisisOrdenPublico": "Incursiones de ACSN en disputa contra subestructuras de AGC que buscan monopolizar los corredores viales, amenazando comerciantes y ganaderos.",
        "alertasDestacadas": "Cobros extorsivos a contratistas y gremios.",
        "coordinates": {"lat": 10.957, "lng": -72.787}
    },
    {
        "id": "guajira-hatonuevo",
        "name": "Hato Nuevo",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 48,
        "votos": 6436,
        "porcentaje": 72.81,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)", "ELN"],
        "subestructuras": ["Subestructura Rufino José Morales (alias Pinocho)", "ELN Frente 6 de Diciembre", "ACSN"],
        "modalidades": ["Extorsión Comercial y Servicios", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Corredor minero con conexión hacia resguardos y Serranía del Perijá.",
        "analisisOrdenPublico": "Ofensiva estructural de ACSN y AGC en el corredor minero. Captura de alias 'Pinocho' por el Gaula. El Frente 6 de Diciembre del ELN genera riesgo en resguardos indígenas.",
        "alertasDestacadas": "Presión sobre resguardos indígenas y sector comercial.",
        "coordinates": {"lat": 11.066, "lng": -72.763}
    },
    {
        "id": "guajira-distraccion",
        "name": "Distracción",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 36,
        "votos": 3491,
        "porcentaje": 57.10,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)", "ELN"],
        "subestructuras": ["Subestructura Rufino José Morales", "ELN Frente 6 de Diciembre", "ACSN"],
        "modalidades": ["Extorsión Comercial y Servicios", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Paso intermedio en el sur de La Guajira hacia la Serranía del Perijá.",
        "analisisOrdenPublico": "Control de economías ilícitas terrestres por AGC; ELN usa la zona rural alta como corredor de abastecimiento hacia Venezuela.",
        "alertasDestacadas": "Extorsión a obras públicas y contratistas locales.",
        "coordinates": {"lat": 10.898, "lng": -72.888}
    },
    {
        "id": "guajira-fonseca",
        "name": "Fonseca",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 99,
        "votos": 18851,
        "porcentaje": 68.00,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)", "ELN", "Segunda Marquetalia"],
        "subestructuras": ["Subestructura Rufino José Morales", "ELN Frente 6 de Diciembre", "Segunda Marquetalia"],
        "modalidades": ["Ataques a Infraestructura", "Tráfico y Acopio de Armamento", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Nodo urbano neurálgico del sur guajiro con conexión directa a la frontera.",
        "analisisOrdenPublico": "Sabotaje logístico del ELN con cilindros bomba en ejes viales hacia Barrancas; AGC domina casco urbano; Segunda Marquetalia usa el corredor alto para tráfico de armas.",
        "alertasDestacadas": "Instalación de artefactos explosivos en vías y comisiones de sicariato.",
        "coordinates": {"lat": 10.885, "lng": -72.854}
    },
    {
        "id": "guajira-dibulla",
        "name": "Dibulla",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 74,
        "votos": 7534,
        "porcentaje": 66.21,
        "gruposArmados": ["ACSN (Los Pachenca)", "Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Javier Cáceres", "Subestructura Cristóbal Duarte", "Subestructura AGC Morelo Peñate"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Estribaciones de la Sierra Nevada frente al Mar Caribe (Mingueo, La Punta).",
        "analisisOrdenPublico": "Fortín histórico de operaciones de las ACSN. Incursión agresiva de AGC para disputar playas y puertos naturales para salida de lanchas rápidas.",
        "alertasDestacadas": "Enfrentamientos en corregimientos costeros y rurales de la Sierra.",
        "coordinates": {"lat": 11.272, "lng": -73.308}
    },
    {
        "id": "guajira-elmolino",
        "name": "El Molino",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 27,
        "votos": 2711,
        "porcentaje": 52.06,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Rufino José Morales", "ELN Frente 6 de Diciembre"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Piedemonte de Perijá en límite con Cesar.",
        "analisisOrdenPublico": "Extorsión y 'vacunas' a comerciantes y finqueros mediante delincuencia tercerizada; ELN usa la zona boscosa alta como corredor fronterizo.",
        "alertasDestacadas": "Distribución masiva de panfletos amenazantes.",
        "coordinates": {"lat": 10.653, "lng": -72.903}
    },
    {
        "id": "guajira-villanueva",
        "name": "Villanueva",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 59,
        "votos": 6317,
        "porcentaje": 53.37,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Rufino José Morales", "ELN Frente 6 de Diciembre", "ACSN Frente Javier Cáceres"],
        "modalidades": ["Extorsión Comercial y Servicios", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Valle del Upar septentrional, nudo de conexión vial con Valledupar.",
        "analisisOrdenPublico": "Presión delincuencial de AGC; ofensiva de expansión de ACSN (Frente Javier Cáceres) en corredores intermunicipales.",
        "alertasDestacadas": "Control social silencioso a través de panfletos.",
        "coordinates": {"lat": 10.608, "lng": -72.981}
    },
    {
        "id": "guajira-urumita",
        "name": "Urumita",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 28,
        "votos": 3317,
        "porcentaje": 60.39,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Rufino José Morales", "ELN Frente 6 de Diciembre", "ACSN Frente Javier Cáceres"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Zona cafetera y agrícola limítrofe con el departamento del Cesar.",
        "analisisOrdenPublico": "Extorsión sistemática a finqueros y comerciantes; tránsito logístico del ELN en la alta montaña.",
        "alertasDestacadas": "Intimidación a productores agrícolas.",
        "coordinates": {"lat": 10.559, "lng": -73.012}
    },
    {
        "id": "guajira-lajaguadelpilar",
        "name": "La Jagua del Pilar",
        "department": "La Guajira",
        "departmentSlug": "la-guajira",
        "region": "Caribe",
        "mesas": 16,
        "votos": 1793,
        "porcentaje": 58.49,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Rufino José Morales", "ELN Frente 6 de Diciembre"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Moderado",
        "posicionGeoestrategica": "Paso estrecho entre Serranía del Perijá y el valle del Cesar.",
        "analisisOrdenPublico": "Uso de la vereda La Palma por el ELN como corredor hacia Venezuela y norte del Cesar; extorsiones rurales de AGC.",
        "alertasDestacadas": "Movilidad clandestina de grupos armados en frontera.",
        "coordinates": {"lat": 10.511, "lng": -73.072}
    },

    # CESAR
    {
        "id": "cesar-valledupar",
        "name": "Valledupar",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 996,
        "votos": 111694,
        "porcentaje": 52.49,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)", "ELN"],
        "subestructuras": ["Subestructura Francisco José Morelos Peñate", "ACSN", "ELN Frente Camilo Torres Restrepo"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento", "Ataques a Infraestructura"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Capital departamental y epicentro comercial del norte del Cesar.",
        "analisisOrdenPublico": "Disputa a sangre y fuego entre el Clan del Golfo y el ELN; incursión urbana de ACSN. Control del narcomenudeo y cobro masivo de vacunas.",
        "alertasDestacadas": "Alertas de seguridad emitidas por la Gobernación del Cesar.",
        "coordinates": {"lat": 10.463, "lng": -73.253}
    },
    {
        "id": "cesar-pueblobello",
        "name": "Pueblo Bello",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 72,
        "votos": 8345,
        "porcentaje": 62.98,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Francisco José Morelos Peñate", "ACSN"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Reclutamiento Forzado de Menores", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Enclave en la Sierra Nevada de Santa Marta habitado por pueblo Arhuaco.",
        "analisisOrdenPublico": "Deterioro grave del orden público. AGC busca el monopolio de rutas serranas hacia La Guajira y Magdalena; extorsión a caficultores y reclutamiento forzado.",
        "alertasDestacadas": "Violaciones de derechos a comunidades indígenas Arhuacas.",
        "coordinates": {"lat": 10.417, "lng": -73.585}
    },
    {
        "id": "cesar-elcopey",
        "name": "El Copey",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 78,
        "votos": 14964,
        "porcentaje": 63.21,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Morelos Peñate", "Subestructura Ferney Antonio López Polo", "ACSN"],
        "modalidades": ["Extorsión Comercial y Servicios", "Ataques a Infraestructura"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Entrada natural a la parte baja occidental de la Sierra Nevada.",
        "analisisOrdenPublico": "Guerra abierta por el control territorial. ACSN utiliza fachadas de préstamos 'gota a gota' para camuflar vacunas y ataca con armas de fuego fachadas comerciales.",
        "alertasDestacadas": "Disparos a fachadas de locales y cobros extorsivos.",
        "coordinates": {"lat": 10.158, "lng": -73.962}
    },
    {
        "id": "cesar-bosconia",
        "name": "Bosconia",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 97,
        "votos": 19101,
        "porcentaje": 58.86,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Francisco José Morelos Peñate", "ACSN Componente Criminal Focalizado"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Cruce vial más importante del Caribe (conecta Cesar, Magdalena, Atlántico y Bolívar).",
        "analisisOrdenPublico": "Centro de acopio y finanzas. AGC recauda cerca de 100 millones de pesos mensuales en extorsiones a comerciantes y transportadores. Infiltración de células de ACSN.",
        "alertasDestacadas": "Extorsión masiva a transportadores y comerciantes.",
        "coordinates": {"lat": 9.977, "lng": -73.883}
    },
    {
        "id": "cesar-elpaso",
        "name": "El Paso",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 87,
        "votos": 12596,
        "porcentaje": 67.40,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Morelos Peñate", "ELN Frente Camilo Torres Restrepo", "ACSN"],
        "modalidades": ["Extorsión Comercial y Servicios", "Minería Ilegal de Oro"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Epicentro de los complejos de carbón más grandes de Colombia (La Loma de Calenturas).",
        "analisisOrdenPublico": "Presión económica sobre el sector minero y comercial. Incursiones rápidas del ELN y ofensiva de ACSN en la variante de La Loma.",
        "alertasDestacadas": "Terror en sectores comerciales de La Loma.",
        "coordinates": {"lat": 9.664, "lng": -73.748}
    },
    {
        "id": "cesar-manaurebalcondelcesar",
        "name": "Manaure Balcón del Cesar",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 30,
        "votos": 2970,
        "porcentaje": 50.31,
        "gruposArmados": ["ELN", "Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["ELN Frente Camilo Torres Restrepo", "Estado Mayor de Bloques y Frentes (EMBF)"],
        "modalidades": ["Tráfico y Acopio de Armamento", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Municipio turístico y agrícola en la Serranía del Perijá, enlace con Catatumbo.",
        "analisisOrdenPublico": "Escenario alterno de repliegue del ELN desde Norte de Santander. Choques armados contra facción disidente EMBF que intenta copar trochas fronterizas.",
        "alertasDestacadas": "Enfrentamientos en zonas rurales periféricas.",
        "coordinates": {"lat": 10.407, "lng": -73.176}
    },
    {
        "id": "cesar-agustincodazzi",
        "name": "Agustín Codazzi",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 155,
        "votos": 17897,
        "porcentaje": 59.23,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Ferney Antonio López Polo", "Comisión Diomedes Dionisio Ortega", "ELN"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Capital agroenergética del Cesar, conecta llanuras mineras con Perijá y Venezuela.",
        "analisisOrdenPublico": "Ubicación codiciada para el narcotráfico y extorsión a megaproyectos agrícolas por el ELN. AGC opera con comisiones urbanas.",
        "alertasDestacadas": "Extorsiones a megaproyectos agroindustriales.",
        "coordinates": {"lat": 10.033, "lng": -73.235}
    },
    {
        "id": "cesar-becerril",
        "name": "Becerril",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 60,
        "votos": 6965,
        "porcentaje": 62.23,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Ferney Antonio López Polo", "ELN Serranía del Perijá"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Eje minero bajo y asentamientos de la etnia Yukpa.",
        "analisisOrdenPublico": "Presión focalizada en comercio y asentamientos indígenas Yukpa. El ELN utiliza zonas altas para vacunas y refugio táctico.",
        "alertasDestacadas": "Vulnerabilidad de comunidades indígenas Yukpa.",
        "coordinates": {"lat": 9.704, "lng": -73.278}
    },
    {
        "id": "cesar-lajaguadeibirico",
        "name": "La Jagua de Ibirico",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 97,
        "votos": 11855,
        "porcentaje": 62.08,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Ferney Antonio López Polo", "ELN Frente Camilo Torres Restrepo"],
        "modalidades": ["Extorsión Comercial y Servicios", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Epicentro de la minería de carbón del Cesar con alto flujo de regalías.",
        "analisisOrdenPublico": "AGC ejerce control hegemónico en casco urbano y La Victoria de San Isidro, extorsionando subcontratistas mineras, estaciones de servicio y transportadores. ELN extorsiona en la parte alta.",
        "alertasDestacadas": "Extorsión sistemática a empresas contratistas del carbón.",
        "coordinates": {"lat": 9.562, "lng": -73.334}
    },
    {
        "id": "cesar-chiriguana",
        "name": "Chiriguaná",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 73,
        "votos": 8359,
        "porcentaje": 60.40,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN", "Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Subestructura Ferney Antonio López Polo", "ELN Frente de Guerra Norte", "GAOr Frente 41 Cacique Upar"],
        "modalidades": ["Ataques a Infraestructura", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Pasadizo estratégico entre la ciénaga y la cordillera oriental.",
        "analisisOrdenPublico": "Retenes ilegales y secuestro de transportadores por el ELN; sicariato por monopolio de narcomenudeo por AGC; incursión del Frente 41 Cacique Upar.",
        "alertasDestacadas": "Robo de carga y retenes ilegales en vías comerciales secundarias.",
        "coordinates": {"lat": 9.362, "lng": -73.602}
    },
    {
        "id": "cesar-curumani",
        "name": "Curumaní",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 96,
        "votos": 9840,
        "porcentaje": 55.29,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Ferney Antonio López Polo", "ELN Frente Camilo Torres Restrepo"],
        "modalidades": ["Ataques a Infraestructura", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Corazón geográfico del Cesar, transición entre centro minero y sur del departamento.",
        "analisisOrdenPublico": "Doble presión violenta: delincuencia sicarial en calles por AGC y atentados terroristas con artefactos explosivos del ELN contra la Policía de Tránsito en San Roque.",
        "alertasDestacadas": "Ataques con explosivos a subestaciones policiales en San Roque.",
        "coordinates": {"lat": 9.187, "lng": -73.554}
    },
    {
        "id": "cesar-tamalameque",
        "name": "Tamalameque",
        "department": "Cesar",
        "departmentSlug": "cesar",
        "region": "Caribe",
        "mesas": 37,
        "votos": 3166,
        "porcentaje": 50.81,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Diomedes Dionisio Ortega Ramos", "ELN Frente Camilo Torres Restrepo"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Municipio ribereño sobre el río Magdalena y la Ciénaga de Zapatosa.",
        "analisisOrdenPublico": "Control de economías fluviales ilícitas y hurto masivo de combustible. Picos de homicidios selectivos y secuestros extorsivos en zonas como Pasa Corriendo y Las Palmas.",
        "alertasDestacadas": "Hurto de combustible y secuestros extorsivos.",
        "coordinates": {"lat": 8.857, "lng": -73.816}
    },

    # MAGDALENA (Selected representative critical municipalities)
    {
        "id": "magdalena-santamarta",
        "name": "Santa Marta",
        "department": "Magdalena",
        "departmentSlug": "magdalena",
        "region": "Caribe",
        "mesas": 1176,
        "votos": 145942,
        "porcentaje": 59.10,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["ACSN Los Pachenca / Oficina del Caribe", "Subestructura Carrascal Gómez", "Subestructura Yepes Cantero"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios", "Ataques a Infraestructura"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Distrito turístico y portuario clave sobre el mar Caribe.",
        "analisisOrdenPublico": "Guerra territorial total por el monopolio del puerto y costas. Atentados con bombas incendiarias contra locales comerciales; vendettas sicariales en Ciudad Equidad, Gaira y Bastidas.",
        "alertasDestacadas": "Uso de artefactos incendiarios y extorsión asfixiante al turismo.",
        "coordinates": {"lat": 11.240, "lng": -74.199}
    },
    {
        "id": "magdalena-cienaga",
        "name": "Ciénaga",
        "department": "Magdalena",
        "departmentSlug": "magdalena",
        "region": "Caribe",
        "mesas": 271,
        "votos": 34984,
        "porcentaje": 65.70,
        "gruposArmados": ["ACSN (Los Pachenca)", "Clan del Golfo / AGC"],
        "subestructuras": ["ACSN", "Subestructura Sergio Antonio Carrascal Gómez", "Subestructura Javier Yepes Cantero"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Conexión entre Sierra Nevada, Ciénaga Grande y troncal a Barranquilla.",
        "analisisOrdenPublico": "ACSN controla zonas montañosas y bananeras; AGC despliega ola de sicariatos urbanos. Intimidaciones en pueblos palafitos de la Ciénaga Grande.",
        "alertasDestacadas": "Afectación a defensores ambientales y turismo ecológico.",
        "coordinates": {"lat": 11.006, "lng": -74.249}
    },
    {
        "id": "magdalena-zonabananera",
        "name": "Zona Bananera (Sevilla)",
        "department": "Magdalena",
        "departmentSlug": "magdalena",
        "region": "Caribe",
        "mesas": 153,
        "votos": 20814,
        "porcentaje": 78.11,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Sergio Antonio Carrascal Gómez", "ACSN"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Corazón de la producción agroindustrial de banano y palma de aceite.",
        "analisisOrdenPublico": "Máxima presión financiera. Asbama denunció incursiones armadas con fusiles a fincas que forzaron la parálisis de más de 19.000 trabajadores bananeros por no pagar extorsiones.",
        "alertasDestacadas": "Parálisis de 19.000 operarios agrícolas por amenazas de muerte.",
        "coordinates": {"lat": 10.771, "lng": -74.156}
    },
    {
        "id": "magdalena-puebloviejo",
        "name": "Pueblo Viejo",
        "department": "Magdalena",
        "departmentSlug": "magdalena",
        "region": "Caribe",
        "mesas": 69,
        "votos": 7164,
        "porcentaje": 64.96,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Sergio Antonio Carrascal Gómez", "ACSN"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Ubicado sobre la Troncal entre Ciénaga y Barranquilla, franja lagunar.",
        "analisisOrdenPublico": "Masacre perpetrada en el corregimiento de Palmira contra pescadores locales por parte del Clan del Golfo en la disputa contra las ACSN por las rutas fluviales.",
        "alertasDestacadas": "Masacre en corregimiento de Palmira e impuestos ilegales a pescadores.",
        "coordinates": {"lat": 10.995, "lng": -74.286}
    },
    {
        "id": "magdalena-sitionuevo",
        "name": "Sitio Nuevo",
        "department": "Magdalena",
        "departmentSlug": "magdalena",
        "region": "Caribe",
        "mesas": 65,
        "votos": 6651,
        "porcentaje": 64.25,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura David Meza Peña", "ACSN"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Reclutamiento Forzado de Menores"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Margen oriental del río Magdalena frente a Barranquilla (Palermo / Puente Pumarejo).",
        "analisisOrdenPublico": "Combates fluviales y terrestres por el control de Palermo. Alerta de la Defensoría por reclutamiento forzado de niños, niñas y adolescentes en corregimientos.",
        "alertasDestacadas": "Alerta temprana por reclutamiento infantil.",
        "coordinates": {"lat": 10.781, "lng": -74.721}
    },
    {
        "id": "magdalena-plato",
        "name": "Plato",
        "department": "Magdalena",
        "departmentSlug": "magdalena",
        "region": "Caribe",
        "mesas": 131,
        "votos": 14214,
        "porcentaje": 58.38,
        "gruposArmados": ["Clan del Golfo / AGC", "ACSN (Los Pachenca)"],
        "subestructuras": ["Subestructura Sergio Antonio Carrascal Gómez", "Subestructura David Meza Peña", "ACSN"],
        "modalidades": ["Extorsión Comercial y Servicios", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Centro neurálgico del Centro del Magdalena y Troncal de los Contenedores.",
        "analisisOrdenPublico": "Control de la Troncal de los Contenedores por el Clan del Golfo; extorsión a bicitaxistas y transportadores pesados por células urbanas.",
        "alertasDestacadas": "Vacunas a transportadores de carga pesada.",
        "coordinates": {"lat": 9.790, "lng": -74.783}
    },

    # ATLÁNTICO
    {
        "id": "atlantico-barranquilla",
        "name": "Barranquilla",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 3434,
        "votos": 375178,
        "porcentaje": 54.18,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Sergio Antonio Carrascal Gómez", "Los Costeños (Castor y Negro Ober)", "Los Pepes (Digno Palomino)"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Distrito portuario e industrial número 1 del Caribe colombiano.",
        "analisisOrdenPublico": "Configuración criminal multicapa: AGC terceriza a pandillas para exportación en puerto, mientras Los Costeños y Los Pepes sostienen una sangrienta guerra urbana con videollamadas extorsivas desde cárceles.",
        "alertasDestacadas": "Extorsiones telefónicas coordinadas desde penitenciarías de alta seguridad.",
        "coordinates": {"lat": 10.968, "lng": -74.781}
    },
    {
        "id": "atlantico-soledad",
        "name": "Soledad",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 920,
        "votos": 115000,
        "porcentaje": 65.33,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Carrascal Gómez", "Los Costeños", "Los Pepes"],
        "modalidades": ["Extorsión Comercial y Servicios", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Segundo municipio más poblado del Atlántico con muelles sobre el río Magdalena.",
        "analisisOrdenPublico": "Ruptura de la tregua entre Los Costeños y Los Pepes provocó un desborde de homicidios por sicariato en barrios como Costa Hermosa, Las Ferias y Villa Adela. AGC financia armamento de largo alcance.",
        "alertasDestacadas": "Pico histórico de vendettas sicariales urbanas.",
        "coordinates": {"lat": 10.918, "lng": -74.764}
    },
    {
        "id": "atlantico-sabanalarga",
        "name": "Sabanalarga",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 77,
        "votos": 10689,
        "porcentaje": 65.31,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Carlos Daniel Fulaye Vargas", "Los Costeños (facciones carcelarias)"],
        "modalidades": ["Ataques a Infraestructura", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Eje conector vial de las subregiones del Atlántico hacia el Canal del Dique.",
        "analisisOrdenPublico": "Alerta 'Do Not Travel' emitida por el Gobierno de Estados Unidos debido a la tasa de homicidios selectivos y disparos a fachadas de locales ordenados por alias 'Negro Ober'.",
        "alertasDestacadas": "Alerta internacional de viaje de EE.UU. por crisis de seguridad.",
        "coordinates": {"lat": 10.633, "lng": -74.920}
    },
    {
        "id": "atlantico-palmar",
        "name": "Palmar de Varela",
        "department": "Atlántico",
        "departmentSlug": "atlantico",
        "region": "Caribe",
        "mesas": 68,
        "votos": 10125,
        "porcentaje": 67.66,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Carlos Daniel Fulaye Vargas", "Los Costeños"],
        "modalidades": ["Extorsión Comercial y Servicios", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Subregión Oriental sobre la margen del río Magdalena.",
        "analisisOrdenPublico": "El alcalde municipal lanzó un angustioso llamado al Gobierno Nacional reportando que más del 80% de los comerciantes locales son víctimas directas de extorsión.",
        "alertasDestacadas": "80% de los comerciantes pagan cuotas extorsivas bajo amenaza.",
        "coordinates": {"lat": 10.741, "lng": -74.754}
    },

    # BOLÍVAR
    {
        "id": "bolivar-cartagena",
        "name": "Cartagena",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 2517,
        "votos": 324123,
        "porcentaje": 65.24,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Nicolás Antonio Urango Reyes", "Pandillas satélites locales"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Puerto marítimo neurálgico del país sobre el mar Caribe.",
        "analisisOrdenPublico": "Plataforma matriz para contaminación de contenedores marítimos con cocaína y despacho de lanchas rápidas en Pasacaballos y Barú. Subcontratación sicarial en Olaya Herrera, El Pozón y Nelson Mandela.",
        "alertasDestacadas": "Contaminación de carga internacional en bahía de Cartagena.",
        "coordinates": {"lat": 10.391, "lng": -75.479}
    },
    {
        "id": "bolivar-norosi",
        "name": "Norosí",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 21,
        "votos": 1788,
        "porcentaje": 65.71,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Erlin Pino Duarte", "ELN Frente Luis José Solano Sepúlveda ('Plan Gonzalo')"],
        "modalidades": ["Minería Ilegal de Oro", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Enclave en la Serranía de San Lucas, rico en yacimientos auríferos.",
        "analisisOrdenPublico": "Punto de máxima violencia bélica. Guerra por minas de oro tradicionales: AGC adelanta incursión armada agresiva contra el 'Plan Gonzalo' del ELN.",
        "alertasDestacadas": "Batallas campales por yacimientos de oro en San Lucas.",
        "coordinates": {"lat": 8.513, "lng": -74.043}
    },
    {
        "id": "bolivar-arenal",
        "name": "Arenal",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 24,
        "votos": 2292,
        "porcentaje": 60.73,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Erlin Pino Duarte", "ELN Frente Luis José Solano Sepúlveda"],
        "modalidades": ["Minería Ilegal de Oro", "Confinamiento y Paros Armados", "Ataques a Infraestructura"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Conexión directa entre la Serranía de San Lucas y el río Magdalena.",
        "analisisOrdenPublico": "Peor crisis humanitaria de la década en el sur de Bolívar. Paros armados, fortificaciones físicas en veredas mineras y confinamiento de la población civil.",
        "alertasDestacadas": "Fortificaciones armadas y campos minados en veredas.",
        "coordinates": {"lat": 8.459, "lng": -73.942}
    },
    {
        "id": "bolivar-sanpablo",
        "name": "San Pablo",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 65,
        "votos": 6645,
        "porcentaje": 57.36,
        "gruposArmados": ["ELN", "Clan del Golfo / AGC"],
        "subestructuras": ["ELN Frente Luis José Solano Sepúlveda", "ELN Compañía Simacota", "AGC Erlin Pino Duarte"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Tráfico y Acopio de Armamento", "Minería Ilegal de Oro"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Extremo sur de Bolívar sobre el río Magdalena Medio.",
        "analisisOrdenPublico": "Teatro de guerra prioritario por control de laboratorios de cocaína y rutas fluviales hacia el río Magdalena. Población civil atrapada en intensos fuegos cruzados.",
        "alertasDestacadas": "Combates en zonas de laboratorio de cocaína y riberas fluviales.",
        "coordinates": {"lat": 7.476, "lng": -73.924}
    },
    {
        "id": "bolivar-cantagallo",
        "name": "Cantagallo",
        "department": "Bolívar",
        "departmentSlug": "bolivar",
        "region": "Caribe",
        "mesas": 26,
        "votos": 3271,
        "porcentaje": 61.16,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["AGC Bloque Central / Erlin Pino Duarte", "ELN Frente Luis José Solano Sepúlveda"],
        "modalidades": ["Ataques a Infraestructura", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Principal enclave petrolero de Bolívar, limítrofe con Antioquia y Santander.",
        "analisisOrdenPublico": "Disputa por rentas petroleras y control de la cuenca del Magdalena. ELN desplegó su 'Plan Gonzalo' para frenar la consolidación del Bloque Central de AGC.",
        "alertasDestacadas": "Presión armada sobre infraestructura de extracción petrolera.",
        "coordinates": {"lat": 7.377, "lng": -73.918}
    },

    # SUCRE
    {
        "id": "sucre-sanonofre",
        "name": "San Onofre",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 154,
        "votos": 16242,
        "porcentaje": 71.90,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Litoral del Golfo de Morrosquillo con manglares (Rincón del Mar, Berrugas).",
        "analisisOrdenPublico": "Hegemonía casi absoluta del Clan del Golfo. Despacho masivo de lanchas Go Fast hacia Centroamérica; férreo control sobre comunidades negras e imposición de toques de queda.",
        "alertasDestacadas": "Silenciamiento de líderes sociales y comunidades negras.",
        "coordinates": {"lat": 9.735, "lng": -75.526}
    },
    {
        "id": "sucre-tolu",
        "name": "Tolú",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 80,
        "votos": 12643,
        "porcentaje": 76.53,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Extorsión Comercial y Servicios", "Reclutamiento Forzado de Menores", "Salida Marítima / Lanchas Go-Fast"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Destino turístico principal del Golfo de Morrosquillo.",
        "analisisOrdenPublico": "Control discreto de alta rentabilidad: vacunas obligatorias a dueños de cabañas, hoteles y agencias turísticas. Instrumentalización de menores de edad como campaneros en playas.",
        "alertasDestacadas": "Reclutamiento informal de menores para vigilancia y microtráfico.",
        "coordinates": {"lat": 9.525, "lng": -75.581}
    },
    {
        "id": "sucre-covenas",
        "name": "Coveñas",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 47,
        "votos": 5441,
        "porcentaje": 55.40,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Ataques a Infraestructura", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Terminal de exportación de crudo de Ocensa y base de Infantería de Marina.",
        "analisisOrdenPublico": "Modus operandi de baja intensidad para no confrontar a la Infantería de Marina, pero con voraz extorsión a proyectos de construcción y condominios turísticos.",
        "alertasDestacadas": "Extorsión a obras de construcción frente al mar.",
        "coordinates": {"lat": 9.408, "lng": -75.682}
    },
    {
        "id": "sucre-sincelejo",
        "name": "Sincelejo",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 631,
        "votos": 89562,
        "porcentaje": 61.73,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Capital departamental de Sucre y centro financiero de la sabana.",
        "analisisOrdenPublico": "Tercerización delincuencial para evadir el cerco policial. Homicidios selectivos contra distribuidores independientes y asesinatos de líderes sociales en el sur de la ciudad.",
        "alertasDestacadas": "Asesinatos selectivos de líderes sociales en comunas periféricas.",
        "coordinates": {"lat": 9.304, "lng": -75.397}
    },
    {
        "id": "sucre-sanbenitoabad",
        "name": "San Benito Abad",
        "department": "Sucre",
        "departmentSlug": "sucre",
        "region": "Caribe",
        "mesas": 73,
        "votos": 6934,
        "porcentaje": 54.12,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Manuel José Gaitán"],
        "modalidades": ["Corredores Fluviales Estratégicos", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Laberinto de humedales y ciénagas que une Córdoba, Sucre y Bolívar.",
        "analisisOrdenPublico": "Centro de acopio y retaguardia en pequeñas lanchas fuera de borda para conectar los laboratorios del sur de Bolívar con el Golfo de Morrosquillo. Extorsión por hectárea de arroz o cabeza de ganado.",
        "alertasDestacadas": "Tráfico en botes a través del complejo cenagoso.",
        "coordinates": {"lat": 8.928, "lng": -75.027}
    },

    # CÓRDOBA
    {
        "id": "cordoba-monteria",
        "name": "Montería",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 1090,
        "votos": 132930,
        "porcentaje": 55.10,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Javier Yepes Cantero"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Capital del departamento y centro financiero del valle del Sinú.",
        "analisisOrdenPublico": "Centro de gravedad financiero y de lavado de activos del Clan del Golfo. Contabilidad centralizada de 'vacunas' a constructoras, transportadoras y clínicas. Red de informantes infiltrada en transportes.",
        "alertasDestacadas": "Lavado de activos a gran escala e infiltración en transportes.",
        "coordinates": {"lat": 8.747, "lng": -75.881}
    },
    {
        "id": "cordoba-tierralta",
        "name": "Tierralta",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 223,
        "votos": 24717,
        "porcentaje": 64.01,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Rubén Darío Ávila", "Subestructura Javier Yepes Cantero"],
        "modalidades": ["Confinamiento y Paros Armados", "Reclutamiento Forzado de Menores", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Puerta de entrada principal al Parque Nacional Natural Paramillo y cuenca del Sinú.",
        "analisisOrdenPublico": "Bastión histórico armado. Dominio de cultivos de coca, laboratorios y campamentos de adoctrinamiento militar en las selvas del Nudo de Paramillo.",
        "alertasDestacadas": "Campos de entrenamiento militar clandestinos en el Paramillo.",
        "coordinates": {"lat": 8.173, "lng": -76.059}
    },
    {
        "id": "cordoba-sanjosedeure",
        "name": "San José de Uré",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 30,
        "votos": 4163,
        "porcentaje": 80.80,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Rubén Darío Ávila", "Subestructura Uldar Cardona Rueda"],
        "modalidades": ["Confinamiento y Paros Armados", "Extorsión Agropecuaria y Ganadera"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Cordillera Occidental limítrofe con el Bajo Cauca antioqueño.",
        "analisisOrdenPublico": "Enclave cocalero de producción industrial de pasta base. Choques armados de contención y homicidios de líderes reclamantes de tierras que apoyan la sustitución voluntaria.",
        "alertasDestacadas": "Asesinatos selectivos de líderes de restitución de tierras.",
        "coordinates": {"lat": 7.995, "lng": -75.539}
    },
    {
        "id": "cordoba-puertolibertador",
        "name": "Puerto Libertador",
        "department": "Córdoba",
        "departmentSlug": "cordoba",
        "region": "Caribe",
        "mesas": 99,
        "votos": 14208,
        "porcentaje": 73.59,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Rubén Darío Ávila", "Subestructura Javier Yepes Cantero"],
        "modalidades": ["Minería Ilegal de Oro", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Vertiente oriental del Parque Paramillo y corredor hacia Antioquia.",
        "analisisOrdenPublico": "Enclave de minería ilegal y producción de coca. Fuerte presencia armada en corregimientos profundos para combatir a la Fuerza Pública.",
        "alertasDestacadas": "Minería ilegal en áreas protegidas del Paramillo.",
        "coordinates": {"lat": 7.893, "lng": -75.671}
    },

    # CHOCÓ
    {
        "id": "choco-quibdo",
        "name": "Quibdó",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 271,
        "votos": 39917,
        "porcentaje": 81.65,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Subestructura Jhon Fredy Orejuela", "ELN Frente de Guerra Occidental", "Los Mexicanos", "Los RPS", "Locos del Norte"],
        "modalidades": ["Extorsión Comercial y Servicios", "Reclutamiento Forzado de Menores", "Minería Ilegal de Oro"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Capital del Chocó y nodo articulador del río Atrato.",
        "analisisOrdenPublico": "Ecosistema criminal atomizado. Alianzas de AGC con Los RPS y del ELN con Los Mexicanos. Fronteras invisibles urbanas, secuestros selectivos y acopio de oro ilegal del Medio Atrato.",
        "alertasDestacadas": "Fronteras invisibles urbanas y guerras sicariales entre pandillas.",
        "coordinates": {"lat": 5.694, "lng": -76.661}
    },
    {
        "id": "choco-bojaya",
        "name": "Bojayá",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 36,
        "votos": 4002,
        "porcentaje": 93.33,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Pablo José Montalvo Cuitiva", "ELN Frente Resistencia Cimarrón"],
        "modalidades": ["Confinamiento y Paros Armados", "Reclutamiento Forzado de Menores", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Cuencas de los ríos Napipí, Opogadó y Bojayá (corredor interoceánico hacia el Pacífico).",
        "analisisOrdenPublico": "Crisis humanitaria severa con 93.33% de apoyo electoral. Guerra frontal por corredores interoceánicos; ELN decreta paros armados y bloqueos de ríos con banderas y explosivos. Confinamiento masivo.",
        "alertasDestacadas": "Paros armados indefinidos y confinamiento de resguardos Emberá.",
        "coordinates": {"lat": 6.549, "lng": -76.898}
    },
    {
        "id": "choco-altobaudo",
        "name": "Alto Baudó",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 53,
        "votos": 6345,
        "porcentaje": 96.69,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Baudó / Leónidas de la Rosa", "ELN Frente Resistencia Cimarrón"],
        "modalidades": ["Confinamiento y Paros Armados", "Minería Ilegal de Oro", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Nacimiento de la cuenca del Baudó que conduce directo al Océano Pacífico.",
        "analisisOrdenPublico": "Votación del 96.69% en medio de guerra total. Campos minados masivos en linderos de escuelas rurales e indígenas Emberá Dobidá con mutilaciones de civiles.",
        "alertasDestacadas": "Campos minados alrededor de escuelas rurales.",
        "coordinates": {"lat": 5.534, "lng": -77.012}
    },
    {
        "id": "choco-acandi",
        "name": "Acandí",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 36,
        "votos": 2554,
        "porcentaje": 49.56,
        "gruposArmados": ["Clan del Golfo / AGC"],
        "subestructuras": ["Subestructura Efrén Vargas Gutiérrez"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Semisumergibles", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Frontera natural directa con Panamá en el Tapón del Darién (Capurganá, Sapzurro).",
        "analisisOrdenPublico": "Control integral del tráfico de migrantes hacia Centroamérica ('tasas de tránsito') y despacho masivo de cargamentos de cocaína en lanchas rápidas y semisumergibles hacia costas panameñas.",
        "alertasDestacadas": "Control del flujo migratorio irregular y caletas costeras de más de 2 toneladas.",
        "coordinates": {"lat": 8.513, "lng": -77.279}
    },
    {
        "id": "choco-istmina",
        "name": "Istmina",
        "department": "Chocó",
        "departmentSlug": "choco",
        "region": "Pacífico",
        "mesas": 80,
        "votos": 9765,
        "porcentaje": 83.86,
        "gruposArmados": ["Clan del Golfo / AGC", "ELN"],
        "subestructuras": ["Subestructura Jhon Fredy Orejuela", "ELN Frente Ernesto Che Guevara"],
        "modalidades": ["Minería Ilegal de Oro", "Extorsión Comercial y Servicios", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Capital comercial de la subregión del río San Juan.",
        "analisisOrdenPublico": "Lavado de activos de AGC y vacunas a comercializadoras de oro y prenderías. El ELN estrangula los corredores fluviales con paros armados aislando corregimientos.",
        "alertasDestacadas": "Estrangulamiento fluvial y paros armados intermitentes.",
        "coordinates": {"lat": 5.161, "lng": -76.685}
    },

    # VALLE DEL CAUCA
    {
        "id": "valle-cali",
        "name": "Cali",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 5158,
        "votos": 682166,
        "porcentaje": 59.64,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Dagoberto Ramos", "Frente Jaime Martínez"],
        "modalidades": ["Reclutamiento Forzado de Menores", "Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Principal centro metropolitano y económico del suroccidente colombiano.",
        "analisisOrdenPublico": "Entrelazamiento entre conflicto rural y delincuencia urbana. La Dagoberto Ramos provee toneladas de marihuana a las 'ollas' del oriente; la Jaime Martínez ejecuta reclutamiento forzado en barrios de ladera.",
        "alertasDestacadas": "Reclutamiento de menores en barrios de ladera hacia frentes del Cauca.",
        "coordinates": {"lat": 3.451, "lng": -76.532}
    },
    {
        "id": "valle-jamundi",
        "name": "Jamundí",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 382,
        "votos": 55757,
        "porcentaje": 63.49,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Jaime Martínez", "Redes de Apoyo RAER"],
        "modalidades": ["Uso de Drones con Explosivos", "Ataques a Infraestructura", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Puerta sur del Valle hacia el cañón del Naya y límites con el Cauca.",
        "analisisOrdenPublico": "Hegemonía armada total del Frente Jaime Martínez. Ataques coordinados de hasta 15 drones con explosivos simultáneos contra tropas militares en Ampudia; blindaje de laboratorios de cocaína.",
        "alertasDestacadas": "Ataques en enjambre de hasta 15 drones con explosivos.",
        "coordinates": {"lat": 3.260, "lng": -76.541}
    },
    {
        "id": "valle-buenaventura",
        "name": "Buenaventura",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 690,
        "votos": 97881,
        "porcentaje": 85.48,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Frente Jaime Martínez", "Los Espartanos / Shottas", "ELN Frente Ernesto Che Guevara"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Semisumergibles", "Extorsión Comercial y Servicios", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Principal puerto del país en el Pacífico, mueve más del 50% del comercio exterior.",
        "analisisOrdenPublico": "85.48% de votación. Camuflaje de cocaína en buques de carga por Los Espartanos; en la cuenca del Bajo Calima el ELN sostiene combates que han desplazado a más de 4.000 personas.",
        "alertasDestacadas": "Desplazamiento forzado de más de 4.000 personas en el Bajo Calima.",
        "coordinates": {"lat": 3.880, "lng": -77.031}
    },
    {
        "id": "valle-dagua",
        "name": "Dagua",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 122,
        "votos": 12098,
        "porcentaje": 55.37,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN"],
        "subestructuras": ["Frente Jaime Martínez", "ELN Frente Manuel Vásquez Castaño"],
        "modalidades": ["Uso de Drones con Explosivos", "Ataques a Infraestructura", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Paso de la Vía al Mar entre Cali y Buenaventura por el cañón de Dagua.",
        "analisisOrdenPublico": "Guerra abierta entre la Jaime Martínez y el ELN. Uso de drones bomba contra puestos militares; amenazas de muerte directas contra la alcaldesa municipal Karol Villarejo.",
        "alertasDestacadas": "Uso recurrente de drones bomba y amenazas directas a la alcaldesa.",
        "coordinates": {"lat": 3.655, "lng": -76.688}
    },
    {
        "id": "valle-tulua",
        "name": "Tuluá",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 513,
        "votos": 53789,
        "porcentaje": 51.36,
        "gruposArmados": ["GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)", "Disidencias FARC (Calarcá / Suárez Briceño)", "Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["La Inmaculada (La Oficina de Tuluá)", "Frente 57 Yair Bermúdez", "Frente Adán Izquierdo"],
        "modalidades": ["Ataques a Infraestructura", "Extorsión Comercial y Servicios", "Uso de Drones con Explosivos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Centro del Valle del Cauca, nodo agroindustrial y comercial.",
        "analisisOrdenPublico": "La Inmaculada monopoliza la canasta familiar (carne, huevos, cebolla) recaudando más de $1.600 millones semestrales con atentados con motobombas y sicariato a jueces/concejales. Guerra declarada con el Frente 57.",
        "alertasDestacadas": "Monopolio criminal de alimentos de primera necesidad y quema de vehículos.",
        "coordinates": {"lat": 4.084, "lng": -76.195}
    },
    {
        "id": "valle-palmira",
        "name": "Palmira",
        "department": "Valle del Cauca",
        "departmentSlug": "valle-del-cauca",
        "region": "Pacífico",
        "mesas": 167,
        "votos": 24978,
        "porcentaje": 72.13,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Adán Izquierdo"],
        "modalidades": ["Uso de Drones con Explosivos", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Segundo municipio más poblado del Valle y puerta a la cordillera Central.",
        "analisisOrdenPublico": "Uso de aeronaves no tripuladas (drones) con explosivos artesanales contra bases militares de la Tercera Brigada. Censos obligatorios a campesinos en la cordillera.",
        "alertasDestacadas": "Drones con explosivos contra batallones militares.",
        "coordinates": {"lat": 3.539, "lng": -76.303}
    },

    # CAUCA
    {
        "id": "cauca-argelia",
        "name": "Argelia",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 73,
        "votos": 15849,
        "porcentaje": 90.76,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN", "Comandos de Frontera (CDF)"],
        "subestructuras": ["Frente Carlos Patiño", "ELN Frente José María Becerra", "Comandos de Frontera"],
        "modalidades": ["Asonadas a Fuerza Pública", "Confinamiento y Paros Armados", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Epicentro absoluto de la economía cocalera del Cañón del Micay.",
        "analisisOrdenPublico": "Votación del 90.76%. Guerra de posiciones. El Frente Carlos Patiño instrumentaliza a campesinos para asonadas violentas y retención de soldados como escudos humanos frente a ofensivas militares.",
        "alertasDestacadas": "Asonadas forzadas a batallones y retención de soldados.",
        "coordinates": {"lat": 2.261, "lng": -77.195}
    },
    {
        "id": "cauca-eltambo",
        "name": "El Tambo",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 145,
        "votos": 22753,
        "porcentaje": 72.99,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN"],
        "subestructuras": ["Frente Carlos Patiño", "ELN Frente Manuel Vásquez Castaño"],
        "modalidades": ["Asonadas a Fuerza Pública", "Minería Ilegal de Oro", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Municipio más extenso del Cauca, entrada al Cañón del Micay.",
        "analisisOrdenPublico": "Zona de guerra total en Huisitó, Playa Rica y El Recuerdo. Coacción armada sobre comités campesinos para cercar tropas; disputas fluviales con el ELN hacia el Pacífico.",
        "alertasDestacadas": "Teatro de guerra abierta en el Cañón del Micay.",
        "coordinates": {"lat": 2.452, "lng": -76.812}
    },
    {
        "id": "cauca-buenosaires",
        "name": "Buenos Aires",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 61,
        "votos": 8688,
        "porcentaje": 64.87,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Segunda Marquetalia"],
        "subestructuras": ["Frente Jaime Martínez", "Segunda Marquetalia Estructura Diomer Cortés"],
        "modalidades": ["Ataques a Infraestructura", "Minería Ilegal de Oro", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Cañón del Naya conectando con los Farallones de Cali y el Pacífico.",
        "analisisOrdenPublico": "Ataques de hasta 10 horas de asedio con volquetas cargadas de dinamita y cilindros bomba que demolieron la Alcaldía Municipal, la estación de Policía y el hospital.",
        "alertasDestacadas": "Destrucción total de la Alcaldía y hospital con volquetas bomba.",
        "coordinates": {"lat": 3.013, "lng": -76.641}
    },
    {
        "id": "cauca-corinto",
        "name": "Corinto",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 59,
        "votos": 12017,
        "porcentaje": 82.06,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["Frente Dagoberto Ramos (Comisión Urbana Santiago Díaz)", "Frente 57 Yair Bermúdez"],
        "modalidades": ["Uso de Drones con Explosivos", "Ataques a Infraestructura", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Enclave de cordillera Central en el norte del Cauca con salida al Valle.",
        "analisisOrdenPublico": "Ataques continuos con enjambres de drones explosivos combinados con francotiradores apostados en las alturas del cañón, provocando confinamiento del casco urbano.",
        "alertasDestacadas": "Hostigamientos simultáneos con drones artillados.",
        "coordinates": {"lat": 3.174, "lng": -76.260}
    },
    {
        "id": "cauca-toribio",
        "name": "Toribío",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 67,
        "votos": 16826,
        "porcentaje": 93.69,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Dagoberto Ramos"],
        "modalidades": ["Reclutamiento Forzado de Menores", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Santuario y centro de gravedad militar del Bloque Occidental disidente.",
        "analisisOrdenPublico": "93.69% de sufragios. Mayor concentración de invernaderos de marihuana tecnificada del país. Reclutamiento forzado de niños en escuelas para entrenamiento en armas y explosivos.",
        "alertasDestacadas": "Extracción forzada de menores de instituciones educativas.",
        "coordinates": {"lat": 2.958, "lng": -76.271}
    },
    {
        "id": "cauca-jambalo",
        "name": "Jambaló",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 33,
        "votos": 8766,
        "porcentaje": 97.19,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Dagoberto Ramos"],
        "modalidades": ["Uso de Drones con Explosivos", "Ataques a Infraestructura", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Zona montañosa indígena autónoma en la cordillera Central.",
        "analisisOrdenPublico": "Votación récord del 97.19%. Resistencia de la Guardia Indígena frente al asedio del Frente Dagoberto Ramos con drones explosivos y destrucción de trincheras y bancos.",
        "alertasDestacadas": "Amenazas de muerte a autoridades del Consejo Regional Indígena.",
        "coordinates": {"lat": 2.793, "lng": -76.326}
    },
    {
        "id": "cauca-santander",
        "name": "Santander de Quilichao",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 250,
        "votos": 45798,
        "porcentaje": 73.27,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Dagoberto Ramos"],
        "modalidades": ["Ataques a Infraestructura", "Minería Ilegal de Oro", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Nodo de interconexión vital sobre la Vía Panamericana entre Cali y Popayán.",
        "analisisOrdenPublico": "Destrucción con explosivos del peaje de Mondomo en la Panamericana para sabotear el transporte nacional. Coadministración armada de yacimientos de oro ilegal en la llanura.",
        "alertasDestacadas": "Dinamitación de infraestructura en la Vía Panamericana.",
        "coordinates": {"lat": 3.009, "lng": -76.484}
    },
    {
        "id": "cauca-guapi",
        "name": "Guapi",
        "department": "Cauca",
        "departmentSlug": "cauca",
        "region": "Andina Suroccidente",
        "mesas": 71,
        "votos": 10097,
        "porcentaje": 94.06,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "ELN", "Comandos de Frontera (CDF)"],
        "subestructuras": ["Frente Rafael Aguilera", "ELN Frente José María Becerra", "Comandos de Frontera"],
        "modalidades": ["Ataques a Infraestructura", "Salida Marítima / Lanchas Go-Fast", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Puerto del Pacífico caucano en la desembocadura de los ríos Guapi y Napi.",
        "analisisOrdenPublico": "Atentado con explosivos de alta potencia contra la Base de la Armada y Policía en casco urbano dejando cráteres gigantes; ELN impone control de cédulas y libre tránsito solo un día a la semana.",
        "alertasDestacadas": "Atentado masivo a base militar y régimen de un solo día de movilidad.",
        "coordinates": {"lat": 2.569, "lng": -77.886}
    },

    # NARIÑO
    {
        "id": "narino-tumaco",
        "name": "San Andrés de Tumaco",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 521,
        "votos": 76219,
        "porcentaje": 88.93,
        "gruposArmados": ["Segunda Marquetalia"],
        "subestructuras": ["Frente Oliver Sinisterra", "Estructura Urías Rondón", "Estructura Alfonso Cano", "Estructura Iván Ríos"],
        "modalidades": ["Semisumergibles", "Salida Marítima / Lanchas Go-Fast", "Reclutamiento Forzado de Menores"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Segundo puerto del Pacífico colombiano y frontera marítima/fluvial con Ecuador.",
        "analisisOrdenPublico": "Complejidad extrema con 88.93% de sufragios. Construcción y despacho de semisumergibles hacia Centroamérica y EE.UU.; ingreso de combustible de contrabando desde Ecuador y reclutamiento forzado.",
        "alertasDestacadas": "Construcción clandestina de semisumergibles transoceánicos.",
        "coordinates": {"lat": 1.798, "lng": -78.815}
    },
    {
        "id": "narino-robertopayan",
        "name": "Roberto Payán",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 38,
        "votos": 6464,
        "porcentaje": 97.79,
        "gruposArmados": ["Segunda Marquetalia"],
        "subestructuras": ["Frente Oliver Sinisterra", "Estructura Alfonso Cano"],
        "modalidades": ["Uso de Drones con Explosivos", "Confinamiento y Paros Armados", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Eje del 'Triángulo de Telembí' sobre las cuencas de los ríos Patía y Telembí.",
        "analisisOrdenPublico": "Votación del 97.79%. Combates de más de una semana consecutiva entre facciones de disidencias con uso de drones de reconocimiento, provocando desplazamientos masivos hacia coliseos.",
        "alertasDestacadas": "Desplazamientos masivos y hacinamiento en coliseos municipales.",
        "coordinates": {"lat": 1.696, "lng": -78.225}
    },
    {
        "id": "narino-barbacoas",
        "name": "Barbacoas",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 92,
        "votos": 13026,
        "porcentaje": 87.82,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Segunda Marquetalia", "Comuneros del Sur / AUN"],
        "subestructuras": ["Frente Franco Benavides", "Frente Iván Ríos", "Comuneros del Sur"],
        "modalidades": ["Minería Ilegal de Oro", "Corredores Fluviales Estratégicos", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Centro urbano bisagra entre Pasto y los ríos Telembí y Patía.",
        "analisisOrdenPublico": "Cobro extorsivo por cada gramo de oro extraído de retroexcavadoras y dragas sobre los afluentes del Telembí ante la caída temporal de precios de la coca.",
        "alertasDestacadas": "Tributos de guerra sobre cada gramo de oro extraído.",
        "coordinates": {"lat": 1.671, "lng": -78.139}
    },
    {
        "id": "narino-pasto",
        "name": "San Juan de Pasto",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 907,
        "votos": 175744,
        "porcentaje": 73.85,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Franco Benavides (células urbanas)"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Capital departamental andina y nodo hacia el puente internacional de Rumichaca.",
        "analisisOrdenPublico": "Infiltración clandestina, lavado de activos y compra masiva de medicamentos y tecnología que luego son despachados a campamentos de la cordillera.",
        "alertasDestacadas": "Abastecimiento tecnológico para campamentos disidentes.",
        "coordinates": {"lat": 1.213, "lng": -77.281}
    },
    {
        "id": "narino-cumbitara",
        "name": "Cumbitara",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 27,
        "votos": 5384,
        "porcentaje": 94.27,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Segunda Marquetalia", "Comuneros del Sur / AUN"],
        "subestructuras": ["Frente Franco Benavides", "Alianza Segunda Marquetalia + Comuneros del Sur + AUN"],
        "modalidades": ["Confinamiento y Paros Armados", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Bisagra que conecta los laboratorios del Cañón del Patía con el litoral.",
        "analisisOrdenPublico": "Votación del 94.27%. Incursiones con fusilería pesada en corregimientos como Sidón y Damasco. Alianza armada tripartita para frenar la avanzada del EMC.",
        "alertasDestacadas": "Combates prolongados de varios días dentro de los caseríos.",
        "coordinates": {"lat": 1.650, "lng": -77.585}
    },
    {
        "id": "narino-policarpa",
        "name": "Policarpa",
        "department": "Nariño",
        "departmentSlug": "narino",
        "region": "Andina Suroccidente",
        "mesas": 42,
        "votos": 9012,
        "porcentaje": 94.03,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)", "Segunda Marquetalia"],
        "subestructuras": ["Frente Franco Benavides", "Segunda Marquetalia"],
        "modalidades": ["Confinamiento y Paros Armados", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Corazón cocalero del cañón del río Patía en la cordillera andina.",
        "analisisOrdenPublico": "Votación del 94.03%. Autoridad de facto casi absoluta en la zona rural; regulación forzada de precios de compra de pasta base y defensa de cristalizaderos.",
        "alertasDestacadas": "Control armado total de las cadenas de valor ilegales.",
        "coordinates": {"lat": 1.558, "lng": -77.466}
    },

    # PUTUMAYO
    {
        "id": "putumayo-puertoasis",
        "name": "Puerto Asís",
        "department": "Putumayo",
        "departmentSlug": "putumayo",
        "region": "Amazonía-Orinoquía",
        "mesas": 160,
        "votos": 25950,
        "porcentaje": 77.53,
        "gruposArmados": ["Comandos de Frontera (CDF)"],
        "subestructuras": ["Coordinadora Guerrillera del Ejército Bolivariano / CDF"],
        "modalidades": ["Extorsión Comercial y Servicios", "Corredores Fluviales Estratégicos", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Capital comercial y nodo fluvial del Bajo Putumayo hacia Perú y Ecuador.",
        "analisisOrdenPublico": "Control de megaproyectos de procesamiento de cocaína y compra de uniformes/medicinas en el comercio urbano. Vacunas a empresas de transporte y subcontratistas.",
        "alertasDestacadas": "Suministro masivo transfronterizo de precursores químicos.",
        "coordinates": {"lat": 0.505, "lng": -76.501}
    },
    {
        "id": "putumayo-valledelguamuez",
        "name": "Valle del Guamuez",
        "department": "Putumayo",
        "departmentSlug": "putumayo",
        "region": "Amazonía-Orinoquía",
        "mesas": 93,
        "votos": 16832,
        "porcentaje": 87.49,
        "gruposArmados": ["Comandos de Frontera (CDF)"],
        "subestructuras": ["Comandos de la Frontera"],
        "modalidades": ["Confinamiento y Paros Armados", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Zona de mayor densidad cocalera del sur del país, frontera con Sucumbíos.",
        "analisisOrdenPublico": "Votación del 87.49%. Control directo de laboratorios industriales de cocaína tecnificados bajo selva espesa; instrumentalización campesina para paros cívicos.",
        "alertasDestacadas": "Tecnificación de cristalizaderos en selva virgen.",
        "coordinates": {"lat": 0.449, "lng": -76.918}
    },
    {
        "id": "putumayo-orito",
        "name": "Orito",
        "department": "Putumayo",
        "departmentSlug": "putumayo",
        "region": "Amazonía-Orinoquía",
        "mesas": 98,
        "votos": 18378,
        "porcentaje": 86.47,
        "gruposArmados": ["Comandos de Frontera (CDF)"],
        "subestructuras": ["Comandos de Frontera"],
        "modalidades": ["Ataques a Infraestructura", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Enclave petrolero del Putumayo con densas zonas rurales.",
        "analisisOrdenPublico": "Millonarias extorsiones a petroleras y empresas contratistas; bloqueos forzados de vías a pozos de bombeo cuando se retrasan los pagos ilegales.",
        "alertasDestacadas": "Presión y parálisis forzada de la industria petrolera.",
        "coordinates": {"lat": 0.667, "lng": -76.872}
    },
    {
        "id": "putumayo-mocoa",
        "name": "Mocoa",
        "department": "Putumayo",
        "departmentSlug": "putumayo",
        "region": "Amazonía-Orinoquía",
        "mesas": 134,
        "votos": 22666,
        "porcentaje": 75.08,
        "gruposArmados": ["Comandos de Frontera (CDF)"],
        "subestructuras": ["RAER Comandos de Frontera"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Capital administrativa del Putumayo y paso hacia el piedemonte andino.",
        "analisisOrdenPublico": "Epicentro administrativo para lavado de activos y reinyección de dinero ilícito en finca raíz y fincas ganaderas; extorsión a consorcios viales.",
        "alertasDestacadas": "Lavado de activos mediante compra de fincas y bienes raíces.",
        "coordinates": {"lat": 1.152, "lng": -76.652}
    },

    # CAQUETÁ
    {
        "id": "caqueta-sanvicente",
        "name": "San Vicente del Caguán",
        "department": "Caquetá",
        "departmentSlug": "caqueta",
        "region": "Amazonía-Orinoquía",
        "mesas": 129,
        "votos": 19074,
        "porcentaje": 62.18,
        "gruposArmados": ["Disidencias FARC (Calarcá / Suárez Briceño)", "Segunda Marquetalia"],
        "subestructuras": ["Bloque Jorge Suárez Briceño (Frente Rodrigo Cadete)", "Frente Miller Perdomo", "Frente Diomer Cortés"],
        "modalidades": ["Uso de Drones con Explosivos", "Extorsión Agropecuaria y Ganadera", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Capital ganadera de la Amazonía y bastión histórico de las FARC.",
        "analisisOrdenPublico": "Salvoconducto obligatorio expedido por el Frente Rodrigo Cadete para poder comprar o vender fincas; macroextorsión tasada por cabeza de ganado y litro de leche; uso de drones con explosivos.",
        "alertasDestacadas": "Salvoconductos obligatorios de la disidencia para venta de tierras.",
        "coordinates": {"lat": 2.115, "lng": -74.770}
    },
    {
        "id": "caqueta-cartagenachaira",
        "name": "Cartagena del Chairá",
        "department": "Caquetá",
        "departmentSlug": "caqueta",
        "region": "Amazonía-Orinoquía",
        "mesas": 73,
        "votos": 11527,
        "porcentaje": 67.19,
        "gruposArmados": ["Disidencias FARC (Calarcá / Suárez Briceño)"],
        "subestructuras": ["Bloque Jorge Suárez Briceño (Frente Rodrigo Cadete)"],
        "modalidades": ["Extorsión Agropecuaria y Ganadera", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Cuenca media del río Caguán, conjunción entre ganadería y coca.",
        "analisisOrdenPublico": "Reuniones forzadas en la selva donde se exige cuota anual a ganaderos; emisión de certificaciones digitales ilegales para autorizar el movimiento de reses en ferris fluviales.",
        "alertasDestacadas": "Certificación digital ilegal para transporte fluvial de ganado.",
        "coordinates": {"lat": 1.350, "lng": -74.842}
    },

    # AMAZONAS
    {
        "id": "amazonas-lapedrera",
        "name": "La Pedrera",
        "department": "Amazonas",
        "departmentSlug": "amazonas",
        "region": "Amazonía-Orinoquía",
        "mesas": 4,
        "votos": 411,
        "porcentaje": 88.00,
        "gruposArmados": ["Disidencias FARC (Calarcá / Suárez Briceño)", "Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Rodrigo Cadete", "Frente Carolina Ramírez"],
        "modalidades": ["Minería Ilegal de Oro", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Último nodo sobre el río Caquetá antes de la frontera con Brasil.",
        "analisisOrdenPublico": "Votación del 88.00%. Disputa a sangre y fuego en lanchas rápidas sobre el río Caquetá por el cobro del gramaje de oro en dragas de aluvión y exportación de cocaína a Brasil.",
        "alertasDestacadas": "Cobro de gramaje en dragas de minería ilegal en el río Caquetá.",
        "coordinates": {"lat": -1.319, "lng": -69.582}
    },
    {
        "id": "amazonas-leticia",
        "name": "Leticia",
        "department": "Amazonas",
        "departmentSlug": "amazonas",
        "region": "Amazonía-Orinoquía",
        "mesas": 134,
        "votos": 1321,
        "porcentaje": 57.28,
        "gruposArmados": ["Comandos de Frontera (CDF)"],
        "subestructuras": ["RAER Comandos de Frontera"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Medio",
        "posicionGeoestrategica": "Trifrontera Colombia-Brasil-Perú sobre el río Amazonas.",
        "analisisOrdenPublico": "Redes de apoyo de civil integradas en el comercio fronterizo, actuando como proveedores mayoristas de alcaloides para carteles brasileños (Comando Vermelho / PCC).",
        "alertasDestacadas": "Enlaces logísticos para carteles del narcotráfico de Brasil.",
        "coordinates": {"lat": -4.215, "lng": -69.940}
    },

    # VAUPÉS
    {
        "id": "vaupes-mitu",
        "name": "Mitú",
        "department": "Vaupés",
        "departmentSlug": "vaupes",
        "region": "Amazonía-Orinoquía",
        "mesas": 64,
        "votos": 7498,
        "porcentaje": 79.50,
        "gruposArmados": ["Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Armando Ríos"],
        "modalidades": ["Reclutamiento Forzado de Menores", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Muy Alto",
        "posicionGeoestrategica": "Capital selvática del Vaupés sobre el río Vaupés hacia Brasil.",
        "analisisOrdenPublico": "Reclutamiento forzado sistemático de menores indígenas mayores de 14 años mediante reuniones clandestinas. Compra masiva de medicinas tropicales y combustible en barcos civiles.",
        "alertasDestacadas": "Reclutamiento de jóvenes indígenas en internados selváticos.",
        "coordinates": {"lat": 1.251, "lng": -70.233}
    },

    # GUAINÍA
    {
        "id": "guainia-inirida",
        "name": "Inírida",
        "department": "Guainía",
        "departmentSlug": "guainia",
        "region": "Amazonía-Orinoquía",
        "mesas": 84,
        "votos": 6846,
        "porcentaje": 58.65,
        "gruposArmados": ["Segunda Marquetalia", "ELN"],
        "subestructuras": ["Frente Acacio Medina", "ELN Frente José Daniel Pérez Carrero"],
        "modalidades": ["Minería Ilegal de Oro", "Corredores Fluviales Estratégicos", "Confinamiento y Paros Armados"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Confluencia de los ríos Guaviare, Atabapo e Inírida, frontera con Venezuela.",
        "analisisOrdenPublico": "Cobro de extorsiones al oro y coltán; manuales de convivencia del ELN que prohíben la navegación nocturna forzando el confinamiento de comunidades indígenas.",
        "alertasDestacadas": "Tráfico de coltán y oro hacia el estado Amazonas venezolano.",
        "coordinates": {"lat": 3.865, "lng": -67.923}
    },

    # VICHADA
    {
        "id": "vichada-cumaribo",
        "name": "Cumaribo",
        "department": "Vichada",
        "departmentSlug": "vichada",
        "region": "Amazonía-Orinoquía",
        "mesas": 93,
        "votos": 9186,
        "porcentaje": 84.69,
        "gruposArmados": ["Segunda Marquetalia", "ELN", "Disidencias FARC (Iván Mordisco / EMC)"],
        "subestructuras": ["Frente Acacio Medina", "ELN Frente José Daniel Pérez Carrero", "Frente Armando Ríos"],
        "modalidades": ["Minería Ilegal de Oro", "Confinamiento y Paros Armados", "Corredores Fluviales Estratégicos"],
        "nivelRiesgo": "Crítico",
        "posicionGeoestrategica": "Municipio más extenso de Colombia, flanqueado por los ríos Meta, Guaviare y Orinoco.",
        "analisisOrdenPublico": "Votación del 84.69%. Extorsión a fondos ambientales de bonos de carbono de resguardos indígenas; puestos de control en el río Vichada y tráfico de coltán y oro a Venezuela.",
        "alertasDestacadas": "Extorsión directa a proyectos ambientales de bonos de carbono.",
        "coordinates": {"lat": 4.258, "lng": -69.800}
    },

    # SAN ANDRÉS
    {
        "id": "sanandres-sanandres",
        "name": "San Andrés",
        "department": "San Andrés y Providencia",
        "departmentSlug": "san-andres",
        "region": "Insular",
        "mesas": 142,
        "votos": 11223,
        "porcentaje": 53.34,
        "gruposArmados": ["Clan del Golfo / AGC", "GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Células satélites AGC", "Pandillas locales de la isla"],
        "modalidades": ["Salida Marítima / Lanchas Go-Fast", "Extorsión Comercial y Servicios"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Archipiélago caribeño a 230 km de Centroamérica.",
        "analisisOrdenPublico": "Aduana marítima estratégica. Reabastecimiento de combustible y almacenamiento en cayos deshabitados para lanchas rápidas antes de dar el salto hacia Centroamérica.",
        "alertasDestacadas": "Uso de cayos solitarios como gasolineras del narcotráfico marítimo.",
        "coordinates": {"lat": 12.584, "lng": -81.700}
    },

    # BOGOTÁ D.C.
    {
        "id": "bogota-bogota",
        "name": "Bogotá D.C.",
        "department": "Bogotá D.C.",
        "departmentSlug": "bogota-dc",
        "region": "Capital",
        "mesas": 17164,
        "votos": 2235514,
        "porcentaje": 59.64,
        "gruposArmados": ["GDOs Urbanos (Costeños/Pepes/Inmaculada/Flacos)"],
        "subestructuras": ["Redes tercerizadas de microtráfico", "Bandas multicrimen"],
        "modalidades": ["Extorsión Comercial y Servicios", "Tráfico y Acopio de Armamento"],
        "nivelRiesgo": "Alto",
        "posicionGeoestrategica": "Capital del país con más de 7 millones de habitantes.",
        "analisisOrdenPublico": "Mercado de consumo interno y narcomenudeo más grande de Colombia; lavado de divisas y contratación de delincuencia común para distribución en comunas y sectores periféricos.",
        "alertasDestacadas": "Mayor flujo de efectivo por consumo de estupefacientes a nivel nacional.",
        "coordinates": {"lat": 4.711, "lng": -74.072}
    }
]

os.makedirs("src/data", exist_ok=True)
os.makedirs("public/data", exist_ok=True)

with open("src/data/municipalities.json", "w", encoding="utf-8") as f:
    json.dump(records, f, ensure_ascii=False, indent=2)

with open("public/data/municipalities.json", "w", encoding="utf-8") as f:
    json.dump(records, f, ensure_ascii=False, indent=2)

print(f"Generated {len(records)} municipalities successfully!")
